### ISSUE TITLE
Exceptions and warining at run completion

### ISSUE THREAD

**Issue by har-wradim** [ebi-pf-team/interproscan#10]
I have been analyzing a big set of protein sequences with interproscan for the last 45 CPU days / 19 real-time days and on the very last step interproscan crashed with a number of warnings and exceptions. It is particularly frustrating because it deleted all of the data in the temp folder while seemingly not creating any output. Right at the moment I have the process in a moribund state still there (see also my settings here):

	$ ps aux | grep [j]ava
	user   27414  235  6.5 16828564 8627544 ?    Sl   Jul07 65790:11 /usr/bin/java -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms256M -Xmx8192M -jar interproscan-5.jar -f GFF3 -f TSV -f HTML -iprlookup --pathways --disable-precalc -b mydir/myoutput -i myfasta.fa -u /my/path

The temp folder contains only one empty subfolder, the final output folder is empty:

	$ ls -l temp/mynode_20160707_094129330_ea9k/jobWriteOutput/
	total 0
	$ ls -l mydir
	total 0

Here is how it looked like sometime before the crash:

	$ ls -l /my/backup/temp/mynode_20160707_094129330_ea9k/
	total 604
	drwxrwxr-x  2 user user   4096 Jul 13 05:33 jobCDD
	drwxrwxr-x  2 user user   4096 Jul 13 01:05 jobCoils
	drwxrwxr-x  2 user user  32768 Jul 16 02:01 jobGene3d
	drwxrwxr-x 35 user user  12288 Jul 13 01:48 jobHAMAP
	drwxrwxr-x  2 user user   4096 Jul  7 09:41 jobLoadFromFasta
	drwxrwxr-x  2 user user   4096 Jul 13 07:21 jobPfam
	drwxrwxr-x  2 user user  24576 Jul 12 23:20 jobPIRSF-3.01
	drwxrwxr-x  2 user user  40960 Jul 13 00:17 jobPRINTS-42.0
	drwxrwxr-x  2 user user  12288 Jul 12 22:57 jobProDom-2006.1
	drwxrwxr-x  2 user user  12288 Jul 12 20:31 jobPrositePatterns
	drwxrwxr-x  2 user user 266240 Jul 12 23:58 jobPrositeProfiles
	drwxrwxr-x  2 user user  81920 Jul 13 00:09 jobSMART
	drwxrwxr-x  2 user user  90112 Jul 13 00:36 jobSuperFamily-1.75
	drwxrwxr-x  2 user user  12288 Jul 12 22:21 jobTIGRFAM-15.0

And here is the log:

	07/07/2016 09:41:23:150 Welcome to InterProScan-5.19-58.0
	07/07/2016 09:41:29:331 Running InterProScan v5 in STANDALONE mode... on Linux
	07/07/2016 09:41:45:776 Loading file myfasta.fa
	07/07/2016 09:41:45:779 Running the following analyses:
	[CDD-3.14,PIRSF-3.01,Pfam-29.0,PRINTS-42.0,ProSiteProfiles-20.119,Coils-2.2.1,Hamap-201605.11,ProSitePatterns-20.119,SUPERFAMILY-1.75,ProDom-2006.1,SMART-7.1,Gene3D-3.5.0,TIGRFAM-15.0]
	Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
	07/07/2016 11:32:02:802 Uploaded/Stored 329021 sequences for analysis
	10/07/2016 06:58:17:688 25% completed
	13/07/2016 00:34:00:987 50% completed
	14/07/2016 19:43:23:438 75% completed
	22/07/2016 00:06:45:536 90% completed
	2016-07-26 17:27:26,394 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@470621c<rs=rs913259387: null>
	2016-07-26 17:27:27,254 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [597714] entries
	2016-07-26 17:36:48,018 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@2a9d0111<rs=rs914012782: null>
	2016-07-26 17:36:48,019 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [600810] entries
	2016-07-26 17:44:00,890 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@10d52e80<rs=rs914755499: null>
	2016-07-26 17:44:00,891 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [603392] entries
	2016-07-26 17:52:34,462 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@59fc52d5<rs=rs915538909: null>
	2016-07-26 17:52:34,462 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [595814] entries
	2016-07-26 18:00:12,711 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@7433e830<rs=rs916271449: null>
	2016-07-26 18:00:12,711 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [603392] entries
	2016-07-26 18:14:11,880 [main] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@462fadef<rs=rs917437921: null>
	2016-07-26 18:14:11,882 [main] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [1] entries
	2016-07-26 18:14:12,280 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.LoadContexts:98] WARN - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@6259d3c4<rs=rs917012334: null>
	2016-07-26 18:14:12,281 [amqEmbeddedWorkerJmsContainer-14] [org.hibernate.engine.loading.internal.CollectionLoadContext:377] WARN - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [600222] entries
	2016-07-26 18:14:33,565 [main] [uk.ac.ebi.interpro.scan.jms.main.Run:1239] WARN - At run completion, unable to delete temporary directory /my/path/temp/mynode_20160707_094129330_ea9k
	Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	Exception in thread "ActiveMQ Broker[localhost] Scheduler" java.lang.OutOfMemoryError: GC overhead limit exceeded
	2016-07-26 18:25:23,811 [ActiveMQ VMTransport: vm://localhost#1-10453] [org.apache.activemq.broker.region.RegionBroker:814] WARN - Caught an exception sending to DLQ: Message ID:mynode-52747-1467877289129-3:1:18:1:2321 dropped=false acked=false locked=true
	java.lang.IllegalStateException: Timer already cancelled.
		at java.util.Timer.sched(Timer.java:397)
		at java.util.Timer.schedule(Timer.java:248)
		at org.apache.activemq.thread.Scheduler.executePeriodically(Scheduler.java:41)
		at org.apache.activemq.broker.region.Queue.start(Queue.java:949)
		at org.apache.activemq.broker.region.AbstractRegion.addDestination(AbstractRegion.java:161)
		at org.apache.activemq.broker.region.RegionBroker.addDestination(RegionBroker.java:348)
		at org.apache.activemq.broker.region.RegionBroker.sendToDeadLetterQueue(RegionBroker.java:804)
		at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
		at org.apache.activemq.advisory.AdvisoryBroker.sendToDeadLetterQueue(AdvisoryBroker.java:505)
		at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
		at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
		at org.apache.activemq.broker.MutableBrokerFilter.sendToDeadLetterQueue(MutableBrokerFilter.java:330)
		at org.apache.activemq.broker.region.PrefetchSubscription.sendToDLQ(PrefetchSubscription.java:540)
		at org.apache.activemq.broker.region.PrefetchSubscription.acknowledge(PrefetchSubscription.java:397)
		at org.apache.activemq.broker.region.AbstractRegion.acknowledge(AbstractRegion.java:526)
		at org.apache.activemq.broker.region.RegionBroker.acknowledge(RegionBroker.java:484)
		at org.apache.activemq.broker.BrokerFilter.acknowledge(BrokerFilter.java:87)
		at org.apache.activemq.broker.BrokerFilter.acknowledge(BrokerFilter.java:87)
		at org.apache.activemq.broker.TransactionBroker.acknowledge(TransactionBroker.java:276)
		at org.apache.activemq.broker.MutableBrokerFilter.acknowledge(MutableBrokerFilter.java:97)
		at org.apache.activemq.broker.TransportConnection.processMessageAck(TransportConnection.java:555)
		at org.apache.activemq.command.MessageAck.visit(MessageAck.java:245)
		at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:338)
		at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:188)
		at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
		at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
		at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:270)
		at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
		at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

I realize that any further experimenting would cost me days, so the question is what causes this problem and how to avoid it. I also guess it is not the behavior one would expect from such a long-running process: to delete temporary files before making sure the outputs were written successfully.

**Comment by har-wradim** [comment]
I silently assumed that it might be possible to resume the run from the point for which I made a backup last time, but how would I do that?

**Comment by gsn7** [comment]
The error says the application ran out of memory and encountered garbage collection problems. The error doesn't say which step failed. However, this type of failure is expected when analysing a large sequence set. To avoid this problem, you should chunk your input into smaller sets. Refer to 
https://github.com/ebi-pf-team/interproscan/wiki/FAQ#8how-to-analyse-a-huge-amount-of-protein-sequences-30000

InterProScan reruns  steps that have failed. It reruns max of 3 times. It is currently not able to recover from the point of catastrophic failure like the one you encounter. It is complicated to implement recovery from this kind of failure. We are working on improving the support to analyse larger input sets.

**Comment by har-wradim** [comment]
Hmm, doesn't it explicitly say "At run completion"? It is rather strange that the process suddenly becomes so memory-thirsty at the crucial moment of writing the output. It would be more robust IMHO to have it write the output on the per-sequence basis.

Anyway, chunking is the solution I am currently trying.
