### ISSUE TITLE
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster.

### ISSUE THREAD

**Issue by Caro-Ca** [ebi-pf-team/interproscan#106]
HI!
After running this code: `~/Interproscan/interproscan-5.38-76.0$ ./interproscan.sh -i ~/Interproscan/interproscan-5.38-76.0/results/R18/CRRNF/R18_CRRNF_fungap_out_prot.faa -iprlookup –goterms -b ~/Interproscan/interproscan-5.38-76.0/results/R18/CRRNF -pa` I got an error, but I don't find the log file. However, this is the error message: 

```
10/10/2019 13:58:46:096 Welcome to InterProScan-5.38-76.0
10/10/2019 13:58:46:099 Running InterProScan v5 in STANDALONE mode... on Linux
10/10/2019 13:59:10:324 Loading file /home/edgar/Interproscan/interproscan-5.38-76.0/results/R18/CRRNF/R18_CRRNF_fungap_out_prot.faa
10/10/2019 13:59:10:326 Running the following analyses:
[CDD-3.17,Coils-2.2.1,Gene3D-4.2.0,Hamap-2019_01,MobiDBLite-2.0,PANTHER-14.1,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProSitePatterns-2019_01,ProSiteProfiles-2019_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
10/10/2019 13:59:34:465 28% completed
10/10/2019 13:59:45:895 57% completed
10/10/2019 13:59:48:751 85% completed
10/10/2019 14:59:48:920 16% completed
10/10/2019 15:59:49:291 17% completed
10/10/2019 16:59:49:536 19% completed
10/10/2019 17:59:49:763 20% completed
10/10/2019 18:59:49:812 22% completed
10/10/2019 19:59:49:914 23% completed
10/10/2019 20:59:50:154 25% completed
10/10/2019 21:59:50:602 26% completed
ERROR: uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/edgar/Interproscan/interproscan-5.38-76.0/temp/pathos_20191010_135856085_f7d1//jobCDD/000000009001_000000010000.blast.raw.out -d data/cdd/3.17/data -m std
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

ERROR: uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/edgar/Interproscan/interproscan-5.38-76.0/temp/pathos_20191010_135856085_f7d1//jobCDD/000000009001_000000010000.blast.raw.out -d data/cdd/3.17/data -m std
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at jdk.internal.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:193)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
        at java.base/java.lang.Thread.run(Thread.java:834)
ERROR: uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener - The exception is :
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/edgar/Interproscan/interproscan-5.38-76.0/temp/pathos_20191010_135856085_f7d1//jobCDD/000000009001_000000010000.blast.raw.out -d data/cdd/3.17/data -m std
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory
```
Thank you in advance for your help.

**Comment by gsn7** [comment]
you should install  the shared library it complains about either by 
sudo apt-get install elfutils
or 
sudo apt-get install libdw1 libdw-dev

**Comment by Caro-Ca** [comment]
is there another code instead of using sudo? Or could you suggest me a way to download it? The website I looked up is not secure.

**Comment by Caro-Ca** [comment]
I guess this one is fine: 
`https://launchpad.net/ubuntu/+source/elfutils/0.170-0.5.0ubuntu1.1`

**Comment by gsn7** [comment]
what is the linux distribution you are running on - Ubuntu, Centos, Mint? and do you have administrative privileges on it? the commands i mentioned or their equivalents depending on the linux distribution you have are the recommended way of installing these libraries

**Comment by Caro-Ca** [comment]
It is Ubuntu and I don't have any administrative privileges to use sudo.

**Comment by Caro-Ca** [comment]
I guess I will try downloading: 
https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/elfutils/0.170-0.5.0ubuntu1.1/elfutils_0.170.orig.tar.bz2
