### ISSUE TITLE
Error using packaged binaries - rpsbproc

### ISSUE THREAD

**Issue by kastman** [ebi-pf-team/interproscan#13]
Hi Interproscan,

I'm trying to run the Interproscan pipeline, but am having trouble with some of the packaged compiled binaries, specifically rpsbproc:

     ./rpsbproc  -h
    ./rpsbproc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./rpsbproc)

This is on RHEL 6.7 x86_64, with the 64bit binaries.

It looks like this is an issue with the upstream NCBI binary - I downloaded both the compiled binary and the src from the [ncbi ftp server](ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc) but the compiled version gives the same GLIBC error, and the src have a bunch of ncbi specific paths & includes and no ./configure file. I'm not sure I want to shave the yak all the way down to compiling it.

The ``rpsblast`` binary does run successfully, and the standard blast I have on my system only contains ``rpsblast``, not ``rpsbproc``. 

I understand this isn't a problem with interproscan per se, but do you have any guidance for me? I checked the wiki [compiling binaries FAQ](https://github.com/ebi-pf-team/interproscan/wiki/FAQ#1what-should-i-do-if-one-of-the-binaries-included-with-interproscan-5-doesnt-work-on-my-system) and [list of specific binary instructions](https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries) but ``rpsbproc`` isn't in there. 

Can you tell me the 'nix version you test on to see if I may just break down and VM / docker image of what I need? Thanks in advance for any suggestions,
Erik

**Comment by kastman** [comment]
PS - [this readme](ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/README) gives instructions on how to compile rpsbproc inside of a standalone blast compilation - I might give that a try. I'll let you know if it succeeds...

**Comment by mifraser** [comment]
Hi Erik,

This will be related to the GLIBC version. We have also seen that error before on RHEL 6 (64-bit) and recompiling from source as you are doing would be required. How did you get on with the instructions, did you manage to recompile it?

The binary supplied with InterProScan should work on RHEL 7 or Ubuntu 14/16.

Kind regards,

Matt

**Comment by kastman** [comment]
@mifraser The NCBI blast download was large, and by the time it finished I got distracted and haven't gone back to recompile yet. When I do recompile I'll upload it for the future so other people can just drop this in to their existing distribution. I wonder if it might just be easier to grab a vm of RHEL7 / Ubuntu 14/16 though; I'm sure there are probably other things compiled against the newer GLIB that I'd also have to recompile as well. Thanks for the quick response; I'll let you know what I end up doing. Closing this issue for now. Best,
Erik

**Comment by justbk** [comment]
@kastman Did you ever end up recompiling BLAST? We have an HPC cluster of CentOS 6 hosts that ran into the same GLIBC issue. I found the same rpsbproc readme as you, but so far it's been a headache chasing down current directions and build instructions just to get this binary going.

**Comment by kastman** [comment]
Hi Brian,

Sorry, I dropped this and didn’t make any progress either. I may swing back around, but it’s fallen pretty far back down the queue again. 

Let me know if you get anywhere with it,

**Comment by abshah** [comment]
Hi @justbk,
I figured out how you could compile rpsbproc on RHEL6/Centos 6.8 machines.
Major issues:
1. CentOS6/RHEL6 ship with ancient versions of GCC and GLIBC (4.4.7, I believe).
2. The [README](ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/README) for rpsblast is not perfect. 

Solution:
Step 1. Install a newer version of GCC and GLIBC using Anaconda or the dev-tools2 repository for CentOS6 or linux brew or your favorite virtual environment manager which supports GLIBCXX_3.4.15 or higher
Step 2. Download the sources of ncbi-blast-2.3.0+. and follow the instructions for compiling rpsblast except for the line "add "RpsbProc" (case sensitive) to the "SUB_PROJ" line.". You should instead do "add "rpsbproc" (case sensitive) to the "SUB_PROJ" line."
Step 3. Configure and compile as per the README for ncbi-blast-2.3.0+

Best,
Abhijeet

**Comment by justbk** [comment]
The good news (thanks everyone!) -- I've successfully compiled this on CentOS 6 using the devtoolset-3-toolchain SCL and both the 2.3.0 (to match the interproscan-packaged version) and the 2.6.0 ncbi-blast source.

The bad -- the recompiled rpsbproc expects single letter switches (compiled from either source version) for its parameters (see: `$ ./rpsbproc -h`), but when the the interproscan pipeline is run on our Condor cluster it seems to be passing the binary more info than it's expecting and then erroring out. Mostly the problem seems to be in prepending a "b" subdir to the expected datapaths, as the other switches are generally ignored.

e.g.:
```
Command: /path/to/newly/compiled/ncbi-blast-2.6.0+/bin/rpsbproc -query /path/to/XXXX00004854.fasta -db data/cdd/3.14/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 Error output from binary:
 Invalid switch 'u', ignored..
 Invalid switch 'r', ignored..
 Invalid switch 'y', ignored..
 Invalid switch 's', ignored..
 Invalid switch 'g', ignored..
 Annotation data loading unsuccessful. Please check the follow data files to make sure they exist and are readable:
        b/cddid.tbl
        b/family_superfamily_links.txt
        b/cdtrack.txt
        b/cddannot.dat
        b/cddannot_generic.dat
        b/bitscore_specific.txt
```

Is there somewhere to modify how this is working to send those inputs correctly?

**Comment by ersgupta** [comment]
hi @justbk, I have the same issue. Is it possible for you to share the rpsbproc that you compiled from source? Thanks

**Comment by abshah** [comment]
Hi @ersgupta , 

Here is a link to my [rpsbproc binary](https://dl.dropboxusercontent.com/u/854292/rpsbproc). The  shared libraries for this look like this:

```
$ ldd rpsbproc
	linux-vdso.so.1 =>  (0x00007ffd4c526000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003f63800000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003f64000000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003f63400000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003862a00000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003f62c00000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x000000385b600000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003862600000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003f63000000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003f62800000)

```

Hope this helps.

Best ,
Abhijeet

**Comment by ersgupta** [comment]
Hi Abhijeet,
Thank you so much. I will let you know how I go with it.

**Comment by mpevs** [comment]
Hi @abshah - I think I might be having the same problem as you - I'm on CentOS 6.7. Do you know if it's possible to get round this problem without installing GCC and GLIBC? I've tried doing that but I'm not sure if it's possible without sudo access, which I don't have. 
The specific error is when running `./configure` in `ncbi-blast-2.6.0+-src` - it reports:

`ncbi-blast-2.6.0+-src/c++/include/corelib/impl/ncbi_atomic_defs.h:94:20: error: atomic: No such file or directory`

I've checked for `ncbi_atomics_defs.h` and it does appear to be there.

Thanks in advance for any help!

**Comment by justbk** [comment]
these were the steps i used to get this built for centos 6.7 

- i only used the `rpsbproc` binary created from this build. the rest of the packaged bins worked as advertised, so just copying that into `ncbi-blast-2.3.0+/bin/` afterward did the trick for our researcher who was requesting this
- don't forget to edit your `interproscan.properties` file, referencing the location of the new/correct rpsbproc where appropriate
- don't forget to "download data files" afterward, as in ftp://ftp.ncbi.nlm.nih.gov/pub/mmdb/cdd/rpsbproc/README

```
# SCLs
yum update -y
yum install -y centos-release-scl-rh

# devtoolset-3-toolchain
# "yum install devtoolset-3-toolchain" vs "yum install install devtoolset-3"
# - basically, you can't install the whole devtoolset, but the toolchain is enough to get gcc (and glibc) and build rpsbproc
# - "Yes, this is unfortunately a known issue. We did not succeeded with rebuilding all eclipse packages for devtoolset-3 and there is currently no man-power to do it (there is quite a lot of bootstrapping needed)."
#   - https://bugzilla.redhat.com/show_bug.cgi?id=1410152
yum install -y devtoolset-3-toolchain

# see old gcc version
gcc --version

# enable scl that has the gcc/glibc we'll need
scl enable devtoolset-3 /bin/bash

# confirm scl is using newer gcc
gcc --version

## rebuild ncbi-blast 2.3.0+ from source, w/ rpsbproc
# ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/README
 
# download 2.3.0 blast source
curl -O ftp://ftp.ncbi.nih.gov/blast/executables/blast+/2.3.0/ncbi-blast-2.3.0+-src.tar.gz
tar -zxvf ncbi-blast-2.3.0+-src.tar.gz && rm -f ncbi-blast-2.3.0+-src.tar.gz && chown -R root:root ncbi-blast-2.3.0+-src && cd ncbi-blast-2.3.0+-src

# download rpsbproc SOURCE
mkdir c++/src/app/rpsbproc
cd c++/src/app/rpsbproc
curl -O ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/rpsbproc.cpp
curl -O ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/Makefile
curl -O ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/Makefile.in
curl -O ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/Makefile.rpsbproc.app
 
# modify makefile
# edit ncbi-blast-2.3.0+-src/c++/src/app/Makefile.in and add "rpsbproc" (case sensitive) to the "SUB_PROJ" line

# do work!
cd ~/ncbi-blast-2.3.0+-src/c++/
./configure
make

# wait for build to finish...

# stop using the devtoolset scl we'd enabled for compiling
exit

# install ncbi-blast-2.3.0+ BINARIES (an old version) to match the interproscan version
curl -O ftp://ftp.ncbi.nih.gov/blast/executables/blast+/2.3.0/ncbi-blast-2.3.0+-x64-linux.tar.gz
tar -zxvf ncbi-blast-2.3.0+-x64-linux.tar.gz && rm -f ncbi-blast-2.3.0+-x64-linux.tar.gz

# copy in the newly compiled rpsbproc
cp ~/ncbi-blast-2.3.0+-src/c++/ReleaseMT/bin/rpsbproc ~/ncbi-blast-2.3.0+/bin/rpsbproc

# show shared libraries
ldd ~/ncbi-blast-2.3.0+/bin/rpsbproc

```

**Comment by mpevs** [comment]
Hi @justbk - Thanks for your help. I'm not able to run `yum` commands because I don't have `sudo` access, but I discovered `gcc 5.1` was available on the system, I just had to add it to my environment. I tried to follow your instructions as closely as possible, but I'm getting the error messages below when running the test script. Would you have any advice?

```
interproscan-5.25-64.0]$ ./interproscan.sh -i test_proteins.fasta -f tsv
26/07/2017 17:46:53:569 Welcome to InterProScan-5.25-64.0
26/07/2017 17:47:00:202 Running InterProScan v5 in STANDALONE mode... on Linux
26/07/2017 17:47:15:517 Loading file /users/40099203/my_interproscan/interproscan-5.25-64.0/test_proteins.fasta
26/07/2017 17:47:15:521 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.1.0,Hamap-201701.18,MobiDBLite-1.0,PANTHER-11.1,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-20.132,ProSiteProfiles-20.132,SFLD-2,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
26/07/2017 17:47:21:632 29% completed
2017-07-26 17:47:27,208 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/2/sfld_sites.annot -a /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.align.out -O /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.out -d /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

2017-07-26 17:47:27,211 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/2/sfld_sites.annot -a /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.align.out -O /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.out -d /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /users/40099203/my_interproscan/interproscan-5.25-64.0/temp/login2.prv.kelvin.compute.estate_20170726_174700200_e8hi//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2017-07-26 17:47:27,213 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2017-07-26 17:47:27,263 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 10 : Run sfld postprocessing binary for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2017-07-26 17:47:27,264 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2017-07-26 17:47:27,264 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:241] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:128)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:375)
2017-07-26 17:47:27,537 [responseMonitorJmsContainer-1] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper:127] WARN - SQL Error: 42102, SQLState: 42S02
2017-07-26 17:47:27,538 [responseMonitorJmsContainer-1] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper:129] ERROR - Table "STEP_EXECUTION" not found; SQL statement:
select stepexecut0_.id as id1_90_0_, stepexecut0_.time_completed as time_com2_90_0_, stepexecut0_.time_created as time_cre3_90_0_, stepexecut0_.exception_first_chunk as exceptio4_90_0_, stepexecut0_.proportion_completed as proporti5_90_0_, stepexecut0_.time_started_running as time_sta6_90_0_, stepexecut0_.state as state7_90_0_, stepexecut0_.step_instance_id as step_ins9_90_0_, stepexecut0_.time_submitted as time_sub8_90_0_, exceptionc1_.step_execution_id as step_exe1_12_1_, exceptionc1_.exception_chunks as exceptio2_12_1_, exceptionc1_.chunk_index as chunk_in3_1_, stepinstan2_.id as id1_91_2_, stepinstan2_.bottom_model as bottom_m2_91_2_, stepinstan2_.bottom_protein as bottom_p3_91_2_, stepinstan2_.step_id as step_id4_91_2_, stepinstan2_.time_created as time_cre5_91_2_, stepinstan2_.top_model as top_mode6_91_2_, stepinstan2_.top_protein as top_prot7_91_2_, dependsupo3_.step_instance_id as step_ins1_93_3_, stepinstan4_.id as depends_2_93_3_, stepinstan4_.id as id1_91_4_, stepinstan4_.bottom_model as bottom_m2_91_4_, stepinstan4_.bottom_protein as bottom_p3_91_4_, stepinstan4_.step_id as step_id4_91_4_, stepinstan4_.time_created as time_cre5_91_4_, stepinstan4_.top_model as top_mode6_91_4_, stepinstan4_.top_protein as top_prot7_91_4_, parameters5_.step_instance_id as step_ins1_92_5_, parameters5_.parameters as paramete2_92_5_, parameters5_.parameters_key as paramete3_5_ from public.step_execution stepexecut0_ left outer join public.exception_chunk exceptionc1_ on stepexecut0_.id=exceptionc1_.step_execution_id inner join public.step_instance stepinstan2_ on stepexecut0_.step_instance_id=stepinstan2_.id left outer join public.step_instance_step_instance dependsupo3_ on stepinstan2_.id=dependsupo3_.step_instance_id left outer join public.step_instance stepinstan4_ on dependsupo3_.depends_upon_id=stepinstan4_.id left outer join public.step_instance_parameters parameters5_ on stepinstan4_.id=parameters5_.step_instance_id where stepexecut0_.id=? [42102-189]
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```

**Comment by justbk** [comment]
@mpevs - that's unrelated to this issue on rpsbproc, however, try https://github.com/ebi-pf-team/interproscan/wiki/KnownIssues for sfld info

**Comment by mpevs** [comment]
@justbk - this sorted it, can run successfully now. Thanks for your help!
