### ISSUE TITLE
interproscan-5.39-77.0 error

### ISSUE THREAD

**Issue by guptapa** [ebi-pf-team/interproscan#132]
Hi, 
I am working with interproscan-5.39-77.0 and got following error:
java.lang.NullPointerException
        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:141)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:193)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:147)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:460)
java.io.IOException: Unable to delete directory /nfs0/BPP/Jaiswal_Lab/GuptaP/chia/genome/augustus_training/new/temp/samwise.cgrb.oregonstate.local_20191223_153304934_nqf/kvstore/matchDB.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1623)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
        at uk.ac.ebi.interpro.scan.jms.master.AbstractMaster.deleteWorkingTemporaryDirectory(AbstractMaster.java:249)
        at uk.ac.ebi.interpro.scan.jms.master.AbstractMaster.cleanUpWorkingDirectory(AbstractMaster.java:264)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.systemExit(StandaloneBlackBoxMaster.java:340)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:302)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:460)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

However this version worked well for me before.
Need help
Thanks.

**Comment by onkar2470** [comment]
I am also getting same error.
This error only comes when i use -t/--seqtype option for giving nucleotide fasta file as input.
For protein seqs it is working fine.
Please reply
Thanx

**Comment by bigfacebig** [comment]
@onkar2470   me too

**Comment by gsn7** [comment]
this bug is fixed in the latest release 5.41-78.0
