### ISSUE TITLE
mobidb_lite.py - TypeError

### ISSUE THREAD

**Issue by JWDebler** [ebi-pf-team/interproscan#147]
I was running interproscan 5.44-79.0 when it crashed. I could narrow the problem down to the `mobidb_lite.py` script. I then tried to run that script on the `test_proteins_new.fasta` and `test_proteins_redundant.fasta` files to make sure it wasn't a problem with my intput data.

This is the complete error message: 

```
python3 /opt/interproscan/interproscan-5.44-79.0/bin/mobidb/2.0/mobidb_lite.py test_proteins_redundant.fasta
Traceback (most recent call last): 
     File "/opt/interproscan/interproscan-5.44-79.0/bin/mobidb/2.0/mobidb_lite.py", line 197, in <module>      
logger.set_logger(ARGS.log, ARGS.logLevel)   
   File "/opt/interproscan/interproscan-5.44-79.0/bin/mobidb/2.0/mdblib/logger.py", line 17, in set_logger
      logging.basicConfig(level=level,
   File "/usr/lib/python3.8/logging/__init__.py", line 1987, in basicConfig
      fmt = Formatter(fs, dfs, style) 
   File "/usr/lib/python3.8/logging/__init__.py", line 576, in __init__
      self._style.validate()
   File "/usr/lib/python3.8/logging/__init__.py", line 428, in validate
      if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object
```

**Comment by gsn7** [comment]
what is the python version for your system?

**Comment by gsn7** [comment]
You might be using python 3.8 which produces that error. We should update the requirements to include this case. 
python 3.6 and 3.7 work fine for us

**Comment by JWDebler** [comment]
yep, running python 3.8.2

**Comment by gsn7** [comment]
next release should run with python 3.8.2 without problems
