### ISSUE TITLE
Interproscan fails at some sequences

### ISSUE THREAD

**Issue by r-mashoodh** [ebi-pf-team/interproscan#149]
Hello

I installed everything. Looked to be working fine. I had no problems running the `test_proteins.fasta` using:
`./interproscan-5.44-79.0/interproscan.sh -i interproscan-5.44-79.0/test_proteins.fasta -f tsv`

But my actual fasta (5000 sequences) throws errors at some but not all sequences, so I split my fasta up into some individual sequences:

This one does not error:
`./interproscan-5.44-79.0/interproscan.sh -i 4514.fa -f tsv`

This one causes an error:
`./interproscan-5.44-79.0/interproscan.sh -i 4513.fa -f tsv
`

The last bit of the error looks like this:
```
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2930) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2911) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2867) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2911) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3552) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	... 28 more
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```
MacOSX 10.15.3 (19D76)
iMac (Retina 5K, 27-inch, 2019)
3.1 GHz 6-Core Intel Core i5
64 GB 2667 MHz DDR4
Linux x86_64
Python Version: 3.5.1
Perl Version: v5.30.0
Java Version: openjdk version "11.0.7" 2020-04-14
File system: APFS
[4513.txt](https://github.com/ebi-pf-team/interproscan/files/4673253/4513.txt)
[4514.txt](https://github.com/ebi-pf-team/interproscan/files/4673254/4514.txt)

I should add that the original fasta contained asteriks and they were removed using the following:
`sed "s/\*//g" < cds.fa > removed.fa
`

I have attached the working and nonworking sequences as text files (but the same file with extensions '.fa' were used in the above examples). I would appreciate any help. Thanks in advance.

**Comment by r-mashoodh** [comment]
This seems to occur with a Python 3.6.0 environment as well.

**Comment by gsn7** [comment]
you have to provide the complete error log, as that would be helpful to identify what might be going on.  the sequences run fine on my installation.

**Comment by r-mashoodh** [comment]
Sorry for the trouble. I think OSX is the issue. Creating an ubuntu environment seemed to work.
