### ISSUE TITLE
Error: Unable to find original database file: work/template/interpro.zip

### ISSUE THREAD

**Issue by rbeinart** [ebi-pf-team/interproscan#18]
I'm getting the below error regarding the original database file - what does this mean?

Thanks!
-Roxanne-

./interproscan.sh -i test_proteins.fasta -f tsv
04/11/2016 12:03:36:304 Welcome to InterProScan-5.21-60.0
04/11/2016 12:03:41:932 Running InterProScan v5 in STANDALONE mode... on Mac OS X
2016-11-04 12:03:41,933 [Thread-7] [uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase:100] FATAL - Unable to find original database file: work/template/interpro.zip
Exception in thread "Thread-7" java.lang.IllegalStateException: Unable to find original database file
	at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.cleanInstalledDatabase(CleanRunDatabase.java:101)
	at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.run(CleanRunDatabase.java:76)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gsn7** [comment]
This errors relate to InterProScan failing to find the InterPro db file 'interpro.zip' that comes with InterProScan, most likely due to issues with the $PATH setting. 
However, even if this is sorted, you will continue to have problems. Your system is an OS X machine and InterProScan has only been tested on Linux.  Refer to https://github.com/ebi-pf-team/interproscan/wiki#supported-platforms

If you have access to a Linux server/cluster, you should install InterProScan there. 
Let us know if you require more help

**Comment by marv123456** [comment]
Hello, I got the same issue, but I'm using Linux, an ArchBang distro, I looked into the folder but that file is not present. Do you know where I can download?
