### ISSUE TITLE
Interproscan showing error  [amqEmbeddedWorkerJmsContainer-10]

### ISSUE THREAD

**Issue by athulmenon** [ebi-pf-team/interproscan#188]
Hi,

I was trying to run the interproscan-5.50-84 version for Fusarium protein sequence. It showed this error while running. 

We tried to run interproscan-5.4 version which showed that we need to update so that it can use the latest database version. We tried to run with --dp variable to make it to run locally, still the error is there. Now old version is also throwing the error.

Older version were running perfectly one week back. Can you please suggest a fix.

/Programs/interproscan/int
erproscan-5.50-84.0/interproscan.sh -i Fusarium_subglutinans_NRRL_66333.proteins.fa -f XML --cpu 12
25/02/2021 11:05:09:611 Welcome to InterProScan-5.50-84.0
25/02/2021 11:05:09:616 Running InterProScan v5 in STANDALONE mode... on Linux
25/02/2021 11:05:27:250 RunID: cues-Precision-WorkStation-T5500_20210225_110525892_7wz
25/02/2021 11:06:06:397 Loading file /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/Fusarium_subglutinans_NRRL_66333.proteins.fa
25/02/2021 11:06:06:408 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.2.0,Hamap-2020_05,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,PIRSF-3.10,PRINTS-42.0,ProSitePatterns-2019_11,ProSiteProfiles-2019_11,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
25/02/2021 11:06:19:165 Uploaded 14039 unique sequences for analysis
2021-02-25 15:55:21,900 [amqEmbeddedWorkerJmsContainer-10] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 22
Command: bin/prosite/ps_scan.pl -d data/prosite/2019_11/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2019_11/prosite_models /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/temp/cues-Precision-WorkStation-T5500_20210225_110525892_7wz//jobPrositeProfiles/000000000001_000000014039.fasta 
Error output from binary:
Segmentation fault (core dumped)
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2019_11/prosite_models/PS01031.prf /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/temp/cues-Precision-WorkStation-T5500_20210225_110525892_7wz//jobPrositeProfiles/000000000001_000000014039.fasta C=6.5 >/Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/temp/cues-Precision-WorkStation-T5500_20210225_110525892_7wz//jobPrositeProfiles//cues-Precision-WorkStation-T5500/tmpdir_000000000001_000000014039//ps436470-1.tmp at bin/prosite/ps_scan.pl line 1960.

OS details.

We are running the tool in java11 conda environment.
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
 
Thank you,
Athul

**Comment by athulmenon** [comment]
I could successfully ran this by splitting the large fasta file into small files and running individually. But do you know a way to combine the results into a single xml? I tried "cat" command but it will just concatenate all the xml files and the opening and ending tags will still make it separate files. Any thoughts?

Thanks,
Athul

**Comment by gsn7** [comment]
You had a Segmentation fault  error and  I would like to reproduce the error. Send me the input fasta that generated the error. You can attach it here.

**Comment by gsn7** [comment]
to combine the interproscan xml files I would do something like:
1. get the header and the footer (use any of the result files)
`head -n 1 result_1.xml > header.txt
`
` tail -n 1 result_1.xml  > footer.txt`
2. Strip the headers and footers from all the results files
`tail -n +2  result_N.xml | head -n -1 >  tmp_result_N.xml`
where `result_N.xml ` is one of your xml file
3. Combine the files
`cat header.txt  tmp_result_1.xml  tmp_result_2.xml  tmp_result_N.xml  footer.txt > final_result.xml`

**Comment by athulmenon** [comment]
Hi,

Please find the attached fasta.
https://drive.google.com/file/d/1Ie5p2nawGtY8qee1i7ciHPbXxW_xxSdG/view?usp=sharing
Thank you for the insight to combine the XML files. 

I started getting errors after running couple of splitted fasta files which have 1000 sequences each. Please check the error below, which is already reported in other threads.

`Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2019_11/prosite_models/PS01031.prf /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7//jobPrositeProfiles/000000000001_000000001000.fasta C=6.5 > /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7//jobPrositeProfiles//cues-Precision-WorkStation-T5500/tmpdir_000000000001_000000001000//ps677140-1.tmp at bin/prosite/ps_scan.pl line 1960.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:197)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-01 14:26:27,944 [amqEmbeddedWorkerJmsContainer-9] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - 2. The exception is :java.lang.IllegalStateException: Command line failed with exit code: 22
Command: bin/prosite/ps_scan.pl -d data/prosite/2019_11/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2019_11/prosite_models /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7//jobPrositeProfiles/000000000001_000000001000.fasta 
Error output from binary:
Segmentation fault (core dumped)
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2019_11/prosite_models/PS01031.prf /Fusarium_subglutinans/Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7//jobPrositeProfiles/000000000001_000000001000.fasta C=6.5 > /Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7//jobPrositeProfiles//cues-Precision-WorkStation-T5500/tmpdir_000000000001_000000001000//ps677140-1.tmp at bin/prosite/ps_scan.pl line 1960.

2021-03-01 14:26:27,944 [amqEmbeddedWorkerJmsContainer-9] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:219] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2021-03-01 14:26:28,010 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 85 : Run ps_scan.pl and pfscan Binary for selected proteins for proteins 1 to 1000 has failed irretrievably.  Available StackTraces follow.
2021-03-01 14:26:28,010 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2021-03-01 14:26:28,010 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:350] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:168) [interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:475) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:168)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:475)
2021-03-01 14:26:29,545 [main] [uk.ac.ebi.interpro.scan.jms.master.AbstractMaster:259] WARN - Master process unable to delete temporary directory /Fsubglutinans_annotation/annotate_results/ipr/temp/cues-Precision-WorkStation-T5500_20210301_141858994_jlk7
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details`


I tried to split the fasta file with 500 sequences each still the issue persists.

Thanks,
Athul

**Comment by gsn7** [comment]
Are you able to run the test command?
`./interproscan.sh -i test_all_appl.fasta -f tsv -dp`

I don't expect you to be having problems running against 500 or 1000 sequences if the test command works. i will try to reproduce the error with the sequences you have sent.

**Comment by gsn7** [comment]
this bug is now fixed in InterProScan-5.51-85.0
