### ISSUE TITLE
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only

### ISSUE THREAD

**Issue by WellJoea** [ebi-pf-team/interproscan#197]
```
IN=/datb/home/wanglab17/11Project/01BombusAnno/00DataBase/PepData/Bombus_terrestris.Bter_1.0.pep.all.fa
OU=/datb/home/wanglab17/11Project/01BombusAnno/03Interproscan
OUT=$OU/Result
mkdir -p $OUT

<<COMMENT
/datb/home/wanglab17/ENV/00software/java/jdk-16+36/bin/java \
#    -XX:ParallelGCThreads=30 \
    -Xms4096M \
    -Xmx91260M \
    -jar \
    /datb/home/wanglab17/ENV/00software/interproscan-5.50-84.0/interproscan-5.jar
COMMENT
/datb/home/wanglab17/ENV/00software/interproscan-5.50-84.0/interproscan.sh \
        -i $IN \
        -b $OUT \
        -T $OUT/temp/. \
        -f TSV XML JSON GFF3 HTML SVG \
        -iprlookup \
        -goterms \
        -pa \
        -t p \
        -cpu 30 
```

get the error

```shell
06/04/2021 18:43:16:687 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.2.0,Hamap-2020_05,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,PIRSF-3.10,PRINTS-42.0,ProSitePatterns-2019_11,ProSiteProfiles-2019_11,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
06/04/2021 18:43:22:340 Uploaded 17031 unique sequences for analysis
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:533)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at jdk.proxy2/jdk.proxy2.$Proxy104.populateProteinMatches(Unknown Source)
	at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:488)
	at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by gsn7** [comment]
this error is non-specific, but maybe try this patch following the instructions below:
```
cd <interproscan_install_dir>
wget ftp://ftp.ebi.ac.uk/pub/databases/interpro/iprscan/5/5.50-84.0/patch/interproscan-5.50-patch.zip
unzip -o  interproscan-5.50-patch.zip
```
and for the  interproscan command add the command option '`--disable-precalc `'

let us know if this works or not for you

**Comment by gsn7** [comment]
some of the non-specific errors seen previously as in this issue are now fixed in InterProScan-5.51-85.0

**Comment by max-l** [comment]
I'm getting this error, in version 5.61-93.0

The invocation is : 

`/nfs3_ib/ip32-ib/openprot-pipelines/prod/containers-libs-and-tools/interproscan-5.61-93.0/interproscan.sh -cpu 23 -b /nfs3_ib/ip32-ib/openprot-pipelines/dp/output/dp_interpro.all-9/interpro_out -pa -T /localscratch/maxl.496115.0 -iprlookup -goterms --input /localscratch/maxl.496115.0/fasta_chunk --formats json
`

In STDOUT I get: 
```
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2021_04,MobiDBLite-2.0,PANTHER-17.0,Pfam-35.0,PIRSF-3.10,PIRSR-2021_05,PRINTS-42.0,ProSitePatterns-2022_05,ProSiteProfiles-2022_05,SFLD-4,SMART-9.0,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
21/04/2023 00:42:14:481 Uploaded 25000 unique sequences for analysis
21/04/2023 00:57:56:048 96% completed
21/04/2023 01:57:56:352 91% completed
21/04/2023 02:57:56:412 98% completed
21/04/2023 03:57:56:512 98% completed
21/04/2023 04:52:12:826 100% done:  InterProScan analyses completed
```

In STDERR:
```
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy103.populateProteinMatches(Unknown Source)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:488)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:829)
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy103.populateProteinMatches(Unknown Source)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:488)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:829)
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy103.populateProteinMatches(Unknown Source)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:488)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by EXJUSTICE** [comment]
@max-l I am getting the same problem, with the exact same STDerr, for Interproscan 5.63-95.0. Will make a new ticket about this .
