### ISSUE TITLE
Could not read provided fasta sequence at bin/phobius/1.01/phobius.pl line 408.

### ISSUE THREAD

**Issue by lecorguille** [ebi-pf-team/interproscan#206]
Hi,

I'm trying to build a singularity image for interproscan (I guess that I'm not the only one)

https://gitlab.com/ifb-elixirfr/cluster/tools/-/blob/master/tools/interproscan/5.51-85.0/image.def

I have an issue with Phobius :

```
$ ./image.sif interproscan.sh -i test_proteins.fasta -f tsv -appl phobius -d
04/05/2021 18:40:13:022 Welcome to InterProScan-5.51-85.0
04/05/2021 18:40:13:025 Running InterProScan v5 in STANDALONE mode... on Linux
04/05/2021 18:40:17:077 RunID: n75_20210504_184016978_b2jp
04/05/2021 18:40:23:858 Loading file /root/singularity_build/interproscan/test_proteins.fasta
04/05/2021 18:40:23:860 Running the following analyses:
[Phobius-1.01]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
04/05/2021 18:40:24:204 33% completed
2021-05-04 18:40:29,295 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 127
Command: bin/phobius/1.01/phobius.pl /root/singularity_build/interproscan/temp/n75_20210504_184016978_b2jp//jobPhobius/000000000001_000000000006.fasta
Error output from binary:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_COLLATE = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LANG = "fr_FR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Phobius ver 1.01
(c) 2004 Lukas Kall, Anders Krogh, Erik Sonnhammer

Could not read provided fasta sequence at bin/phobius/1.01/phobius.pl line 408.

2021-05-04 18:40:29,298 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/phobius/1.01/phobius.pl /root/singularity_build/interproscan/temp/n75_20210504_184016978_b2jp//jobPhobius/000000000001_000000000006.fasta
Error output from binary:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_COLLATE = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LANG = "fr_FR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Phobius ver 1.01
(c) 2004 Lukas Kall, Anders Krogh, Erik Sonnhammer

Could not read provided fasta sequence at bin/phobius/1.01/phobius.pl line 408.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201) ~[interproscan-management-5.51-85.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-05-04 18:40:29,305 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/phobius/1.01/phobius.pl /root/singularity_build/interproscan/temp/n75_20210504_184016978_b2jp//jobPhobius/000000000001_000000000006.fasta
Error output from binary:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_COLLATE = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LANG = "fr_FR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
[...]
```

```
$ tree temp/n75_20210504_184219520_58my/
temp/n75_20210504_184219520_58my/
├── jobFinaliseInitialSteps
├── jobLoadFromFasta
├── jobPhobius
│   ├── 000000000001_000000000006.fasta
│   └── 000000000001_000000000006.raw.out
└── kvstore
    ├── entryDB
    │   ├── 000005.log
    │   ├── CURRENT
    │   ├── LOCK
    │   └── MANIFEST-000004
    ├── matchDB
    │   ├── 000003.log
    │   ├── CURRENT
    │   ├── LOCK
    │   └── MANIFEST-000002
    ├── NucleotideDB
    │   ├── 000003.log
    │   ├── CURRENT
    │   ├── LOCK
    │   └── MANIFEST-000002
    ├── proteinDB
    │   ├── 000003.log
    │   ├── CURRENT
    │   ├── LOCK
    │   └── MANIFEST-000002
    └── proteinNotInLookupDB
        ├── 000003.log
        ├── CURRENT
        ├── LOCK
        └── MANIFEST-000002
```

Do you have any clue to help me?

Thanks!

**Comment by gsn7** [comment]
this is the case where the error displayed is completely misleading.

check if the phobius binary is 32 bit
`file bin/phobius/1.01/decodeanhmm |grep 32-bit`

if it is 32 bit, replacing it with a 64 bit binary from http://phobius.sbc.su.se/data.html will solve the problem.

By the way, since Phobius predicts every region that TMHMM predicts youdon't need to have both. Just keep Phobius.

We have a docker container here https://hub.docker.com/r/interpro/interproscan, without licenced applications like phobius.  This can be used with singularity, but maybe we should consider a singularity image as well.

**Comment by lecorguille** [comment]
You were right 👍 
https://gitlab.com/ifb-elixirfr/cluster/tools/-/blob/master/tools/interproscan/5.51-85.0/image.def#L90 

Indeed, it could be great to provide to your user a singularity image or at least a def file to include the licenced applications.

You can grab our [image.def](https://gitlab.com/ifb-elixirfr/cluster/tools/-/blob/master/tools/interproscan/5.51-85.0/image.def) to begin with if you want.
Since you already provide a docker image (I didn't manage to find the Dockerfile), we should be able to bootstrap from it and only deal with the additional licenced files.
