### ISSUE TITLE
pfscanV3 throws "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by RNieuwenhuis** [ebi-pf-team/interproscan#215]
Hi,

Using `v5.52-86.0` I constantly run into the following error:

```
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2021_01/prosite_patterns.dat --pfscan bin/prosite/pfscanV3 -b data/prosite/2021_01/evaluator.dat -r -s -o ipro /lustre/scratch/WUR/PRI/nieuw133/tmp/login0_20210706_221359143_k3qx//jobPrositePatterns/000000000001_000000000171.fasta
Error output from binary:
pfscanV3 is not meant to be used with a single profile, use pfsearchV3 to get better performance in such case.
Could not execute bin/prosite/pfscanV3 --matrix-only -o4 -L-1 /tmp/ps648070-1.tmp /tmp/ps648070-3.tmp  > /tmp/ps648070-2.tmp: Inappropriate ioctl for device at bin/prosite/ps_scan.pl line 1751.
```

I have no idea how to solve this error and would be very pleased with your help.

**Comment by matthiasblum** [comment]
Hi @RNieuwenhuis and @lecorguille,

Could you try to change to property below in the 'interproscan.properties' file (in the root directory of InterProScan)?

Change:

```
pfsearchv3.binary.switches.prositeprofiles=-f -o 7
```

to:

```
pfsearchv3.binary.switches.prositeprofiles=-f -o 7 --no-affinity
```

and let us now if this resolves the issue?

Thank you.

**Comment by jadeleconte** [comment]
Hello ! Thanks for the answer, I'm working with @lecorguille and we tried to do that, but sadly we're still getting the error...

Complete error log is attached here ([slurm.n80.19978224.txt](https://github.com/ebi-pf-team/interproscan/files/7177440/slurm.n80.19978224.txt))... It seems to run just fine when we remove Prosite from the analyses. Is there any other way to try and make Prosite work ?

Thanks again !

**Comment by wresch** [comment]
Hello. I ran into the same issue. I got past this by downloading the newest prosite source (3.2.10) and compiling with affinity turned off. However, the pipeline still fails because the output can't be parsed:

```
interproscan.sh --goterms --pathways -f svg,tsv,html -T ./temp --disable-precalc -i ecoli_benchmark.fa.chunk0001
30/09/2021 10:07:35:242 Welcome to InterProScan-5.52-86.0
30/09/2021 10:07:35:245 Running InterProScan v5 in STANDALONE mode... on Linux
30/09/2021 10:07:44:793 RunID: cn2836_20210930_100744573_i3as
30/09/2021 10:07:58:020 Loading file /lscratch/24275267/ecoli_benchmark.fa.chunk0001
30/09/2021 10:07:58:023 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.3.0,Hamap-2020_05,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,Phobius-1.01,PIRSF-3.10,PIRSR-2021_02,PRINTS-42.0,ProSitePatterns-2021_01,ProSiteProfiles-2021_01,SFLD-4,SignalP_EUK-4.1,SignalP_GRAM_NEGATIVE-4.1,SignalP_GRAM_POSITIVE-4.1,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
30/09/2021 10:10:43:866 25% completed
2021-09-30 10:10:48,828 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-09-30 10:10:48,903 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26)
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66)
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.base/java.lang.Thread.run(Thread.java:835)
2021-09-30 10:10:48,906 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-09-30 10:10:49,156 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:176] WARN - StepInstance 59 is being re-run following a failure.
2021-09-30 10:10:59,683 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-09-30 10:10:59,686 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26)
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66)
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.base/java.lang.Thread.run(Thread.java:835)
2021-09-30 10:10:59,687 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-09-30 10:10:59,809 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:176] WARN - StepInstance 59 is being re-run following a failure.
2021-09-30 10:11:05,024 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-09-30 10:11:05,025 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.NullPointerException: Alignment must not be null
	at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75)
	at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26)
	at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66)
	at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.base/java.lang.Thread.run(Thread.java:835)
2021-09-30 10:11:05,026 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-09-30 10:11:05,087 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 59 : Parse the output from the Prosite binary for proteins 1 to 600 has failed irretrievably.  Available StackTraces follow.
2021-09-30 10:11:05,087 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2021-09-30 10:11:05,087 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:349] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167) [interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:495) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:495)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
cp: cannot stat ‘ecoli_benchmark.fa.chunk0001.*’: No such file or directory

**Comment by wresch** [comment]
I take it back - after further troubleshooting the error above turns out to have been an issue with my wrapper script. So the upshot is that compiling prosite with `cmake -DUSE_AFFINITY=OFF ..` did the trick

**Comment by Juke34** [comment]
I would be easier to use directly the container: https://quay.io/repository/biocontainers/interproscan
