### ISSUE TITLE
NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) 

### ISSUE THREAD

**Issue by xiongqian123456789** [ebi-pf-team/interproscan#223]
Hello, Im trying to run InterProScan-5.52-86.0  in linux 64bit, JAVA-11, python 3.7. 
runing interproscan.sh -h showed normal operation 
But when testing:  interproscan.sh -i test_all_appl.fasta -f tsv -dp
I get the following error:
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListener    Container.java:1189)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageList    enerContainer.java:1179)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.j    ava:1076)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-08-24 15:26:21,604 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecutio    n with errors - stepName: stepLoadFromFastaIntoDB
2021-08-24 15:26:21,637 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 1 : Load prote    ins from a fasta file and load into DB before creating required JobInstance objects for proteins null to null has failed irretrievably.  Avai    lable StackTraces follow.
2021-08-24 15:26:21,637 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a     non-zero exit status.
2021-08-24 15:26:21,637 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:349] ERROR - Exception thrown by StandaloneBlackB    oxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interprosca    n-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167) [interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:495) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:495)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

And I read the issues #217, and installed the libpcre3-dev (https://github.com/tdtadeu/libpcre/archive/refs/heads/master.zip) with the package from github cause I have no root access. 

Appreciate your help.

**Comment by Irene-cano-cejas** [comment]
Hello, I am having the same error, any help please?
