### ISSUE TITLE
java.lang.NullPointerException: Alignment must not be null

### ISSUE THREAD

**Issue by lecorguille** [ebi-pf-team/interproscan#236]
With @jadeleconte, we went though those issue:
 - https://github.com/ebi-pf-team/interproscan/issues/215
 - https://github.com/sib-swiss/pftools3/issues/25

Our current versions:
```
$ interproscan.sh --version
InterProScan version 5.52-86.0
InterProScan 64-Bit build  (requires Java 11)

$ /opt/interproscan/bin/prosite/pfscan --version
pfscan 2.3 revision 5.d
$ /opt/interproscan/bin/prosite/pfscanV3
 Version 3.2.11 built on Nov  8 2021 at 09:53:10.
```

Our current error:
```
08/11/2021 12:36:17:742 Welcome to InterProScan-5.52-86.0
08/11/2021 12:36:17:745 Running InterProScan v5 in STANDALONE mode... on Linux
08/11/2021 12:36:22:737 RunID: n75_20211108_123622495_flb7
08/11/2021 12:36:29:460 Loading file /projet/sbr/cyanorak/current/common/genomics/functional_annotation/interproscan/3-pfam_go_interpro_prosites_TIGRfam_2021-08-24/./input_interproscan/Pro_AS9601_NO_STAR.fasta
08/11/2021 12:36:29:462 Running the following analyses:
[Pfam-33.1,ProSitePatterns-2021_01,ProSiteProfiles-2021_01,SignalP_GRAM_NEGATIVE-4.1,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
08/11/2021 12:36:49:976 85% completed
2021-11-08 12:37:03,673 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
        at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-11-08 12:37:03,679 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
2021-11-08 12:37:03,679 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-11-08 12:37:03,790 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:176] WARN - StepInstance 31 is being re-run following a failure.
2021-11-08 12:37:21,632 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
        at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-11-08 12:37:21,633 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
2021-11-08 12:37:21,634 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-11-08 12:37:21,685 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:176] WARN - StepInstance 31 is being re-run following a failure.
2021-11-08 12:37:26,688 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NullPointerException: Alignment must not be null
        at uk.ac.ebi.interpro.scan.model.raw.alignment.CigarAlignmentEncoder.encode(CigarAlignmentEncoder.java:51) ~[interproscan-model-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:75) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.prosite.PrositePfsearchMatchParser.createMatch(PrositePfsearchMatchParser.java:26) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.io.match.AbstractLineMatchParser.parse(AbstractLineMatchParser.java:66) ~[interproscan-io-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.management.model.implementations.ParseStep.execute(ParseStep.java:101) ~[interproscan-management-5.52-86.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at com.sun.proxy.$Proxy142.executeInTransaction(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-11-08 12:37:26,688 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
2021-11-08 12:37:26,689 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesParseRawOutput
2021-11-08 12:37:26,693 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 31 : Parse the output from the Prosite binary for proteins 1 to 1925 has failed irretrievably.  Available StackTraces follow.
2021-11-08 12:37:26,693 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2021-11-08 12:37:26,693 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:349] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167) [interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:495) [interproscan-5.jar:?]
```

**Comment by abretaud** [comment]
I'm having the same problem with 5.54-87.0, any clue from anyone?

**Comment by abretaud** [comment]
Ok problem solved for me: I still had the `--no-affinity` option set in `pfsearchv3.binary.switches.prositeprofiles`, while using [pftools 3.2.11](https://github.com/sib-swiss/pftools3/releases/tag/v3.2.11) which doesn't have this option anymore. The jobPrositeProfiles output files were full of pftools usage info.
I just removed the --no-affinity option and now it works

**Comment by courtneystairs** [comment]
Hi Anthony! I'm getting the same error however I built pftools with the no-affinity option. 

Can you point me to where I can find the `pfsearchv3.binary.switches.prositeprofiles` file and where I could make the edits?  I am struggling to find it in the interproscan directories. 

Thanks :)

**Comment by abretaud** [comment]
Hi @courtneystairs,
`pfsearchv3.binary.switches.prositeprofiles` is in the interproscan.properties file

**Comment by Lsz-20** [comment]
@abretaud i have the same question,but my 'pfsearchv3.binary.switches.prositeprofiles=-f -o 7;' has no --no-affinity
the version is 5.54
Thanks!

**Comment by aagatam** [comment]
Hi! Did anyone solve it? I'm running into the same problem in version  5.55.

**Comment by matthiasblum** [comment]
Recent builds of InterProScan should not be affected by this issue. Otherwise, please try to Docker image: https://hub.docker.com/r/interpro/interproscan
