### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'bin/hmmer/hmmer3/3.3/hmmpress'

### ISSUE THREAD

**Issue by RinaYona** [ebi-pf-team/interproscan#252]
Hi,

After installing InterProScan, I put the command $ python3 initial_setup.py, and the error was displayed as following.

Checking any hmm models that need indexing ... this may take a few minutes
Traceback (most recent call last):
  File "initial_setup.py", line 75, in <module>
    run_hmmpress(hmmpress33_path, hmmpress_force, hmms_path.strip())
  File "initial_setup.py", line 55, in run_hmmpress
    call([hmmpress_path, hmms_path])
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'bin/hmmer/hmmer3/3.3/hmmpress'

Please let me know any idea.

**Comment by matthiasblum** [comment]
Hi @RinaYona ,

What happens if you run `bin/hmmer/hmmer3/3.3/hmmpress`?

**Comment by leili-plantmicrobe** [comment]
> 
Hi @matthiasblum ,
I also got the similar error when run python3 initial_setup.py.

Checking any hmm models that need indexing ... this may take a few minutes
Traceback (most recent call last):
  File "/Users/lilei/Desktop/RGAugury/interproscan/interproscan-5.56-89.0/initial_setup.py", line 75, in <module>
    run_hmmpress(hmmpress33_path, hmmpress_force, hmms_path.strip())
  File "/Users/lilei/Desktop/RGAugury/interproscan/interproscan-5.56-89.0/initial_setup.py", line 55, in run_hmmpress
    call([hmmpress_path, hmms_path])
  File "/Users/lilei/opt/miniconda3/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/lilei/opt/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/lilei/opt/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'bin/hmmer/hmmer3/3.3/hmmpress'

when i run "bin/hmmer/hmmer3/3.3/hmmpress"
it is "zsh: exec format error: bin/hmmer/hmmer3/3.3/hmmpress"

I am new in using this. Thanks a lot!

**Comment by matthiasblum** [comment]
Hi @leili-plantmicrobe,

It looks like your operating system is macOS. Is this the case? InterProScan is only supported on Linux systems, as included binaries (such as `hmmpress`) were compiled for Linux.
