### ISSUE TITLE
 ERROR - Command line failed with exit code: 1

### ISSUE THREAD

**Issue by juno-jli** [ebi-pf-team/interproscan#258]
hi, when I use interproscan for my data  , an error has occur
I can't  solve  this problem by my self ，can you tell me how to fix this？
thank you 

/home/lijuan.chen/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/interproscan2.sh --cpu 200  -i query_all.fasta -f XML -f tsv -b  ./interproscan -dp
02/04/2022 16:51:24:908 Welcome to InterProScan-5.30-69.0
02/04/2022 16:51:48:863 Running InterProScan v5 in STANDALONE mode... on Linux
02/04/2022 16:52:39:199 Loading file /AnalysisWorkSpace/hj/M-GSGC0325919/query_all.fasta
02/04/2022 16:52:39:203 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-1.5,PANTHER-12.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2022-04-02 16:53:01,190 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: python3 bin/mobidb/1.5/mobidb_lite.py /AnalysisWorkSpace/hj/M-GSGC0325919/temp/localhost.localdomain_20220402_165148861_g9xv//jobMobiDBLite/000000004001_000000005000.fasta 
Error output from binary:
Traceback (most recent call last):
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mobidb_lite.py", line 194, in <module>
    logger.set_logger(ARGS.log, ARGS.logLevel)
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mdblib/logger.py", line 17, in set_logger
    logging.basicConfig(level=level,
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 2015, in basicConfig
    fmt = Formatter(fs, dfs, style)
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 574, in __init__
    self._style.validate()
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 426, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object

2022-04-02 16:53:01,197 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: python3 bin/mobidb/1.5/mobidb_lite.py /AnalysisWorkSpace/hj/M-GSGC0325919/temp/localhost.localdomain_20220402_165148861_g9xv//jobMobiDBLite/000000004001_000000005000.fasta 
Error output from binary:
Traceback (most recent call last):
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mobidb_lite.py", line 194, in <module>
    logger.set_logger(ARGS.log, ARGS.logLevel)
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mdblib/logger.py", line 17, in set_logger
    logging.basicConfig(level=level,
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 2015, in basicConfig
    fmt = Formatter(fs, dfs, style)
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 574, in __init__
    self._style.validate()
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 426, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2022-04-02 16:53:01,198 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepMobiDBRunBinary
2022-04-02 16:53:01,691 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 306 is being re-run following a failure.
2022-04-02 16:53:02,826 [amqEmbeddedWorkerJmsContainer-11] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: python3 bin/mobidb/1.5/mobidb_lite.py /AnalysisWorkSpace/hj/M-GSGC0325919/temp/localhost.localdomain_20220402_165148861_g9xv//jobMobiDBLite/000000005001_000000006000.fasta 
Error output from binary:
Traceback (most recent call last):
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mobidb_lite.py", line 194, in <module>
    logger.set_logger(ARGS.log, ARGS.logLevel)
  File "/blast2go_commandline/my_interproscan/interproscan-5.30-69.0/bin/mobidb/1.5/mdblib/logger.py", line 17, in set_logger
    logging.basicConfig(level=level,
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 2015, in basicConfig
    fmt = Formatter(fs, dfs, style)
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 574, in __init__
    self._style.validate()
  File "/usr/local/soft/miniconda3/lib/python3.9/logging/__init__.py", line 426, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object

**Comment by yyy19981022** [comment]
hi, i had the same problem. Have you solved it?
