### ISSUE TITLE
problems_ERROR - Command line failed with exit code: 139

### ISSUE THREAD

**Issue by ijulca** [ebi-pf-team/interproscan#29]
Hi,
I'm having this problem with some files:

30/05/2017 09:40:11:480 Welcome to InterProScan-5.24-63.0
30/05/2017 09:40:20:600 Running InterProScan v5 in STANDALONE mode... on Linux
30/05/2017 09:40:32:183 Loading file Dnoxia.faa.00105.fa
30/05/2017 09:40:32:189 Running the following analyses:
[CDD-3.14,Coils-2.2.1,Gene3D-4.1.0,Hamap-201701.18,MobiDBLite-1.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-20.132,ProSiteProfiles-20.132,SFLD-2,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
30/05/2017 09:41:00:421 26% completed
30/05/2017 09:41:18:407 50% completed
30/05/2017 09:41:42:448 75% completed
2017-05-30 09:42:01,533 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 139
Command: bin/sfld/sfld_postprocess -s data/sfld/2/sfld_sites.annot -a /home//tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.align.out -O /home//tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.out -d /home//tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.domtblout.out -o /home//tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091_one.raw.out 
Error output from binary:

2017-05-30 09:42:01,535 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 139
Command: bin/sfld/sfld_postprocess -s data/sfld/2/sfld_sites.annot -a /home/tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.align.out -O /home/tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.out -d /home/tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091.raw.domtblout.out -o /home/tmp/titan_20170530_094020591_evo//jobSFLD/000000000002_000000000091_one.raw.out 
Error output from binary:

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2017-05-30 09:42:01,536 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2017-05-30 09:42:01,631 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 92 : Run sfld postprocessing binary for selected proteins for proteins 2 to 91 has failed irretrievably.  Available StackTraces follow.
2017-05-30 09:42:01,632 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2017-05-30 09:42:01,632 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:227] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:115)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:375)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by gsn7** [comment]
Hi, there is a small bug in the sfld post processor shipped with InterProScan-5.24-63.0 and this happens only on some input sequences. We have a fix. Unzip ftp://ftp.ebi.ac.uk/pub/databases/interpro/iprscan/5/bin/sfld_binary.zip 
into bin/sfld/

**Comment by ijulca** [comment]
thank you. Now it is working perfectly :)
