### ISSUE TITLE
.h3i format error with all Databases in the latest version.

### ISSUE THREAD

**Issue by jose-martinez-fignoni** [ebi-pf-team/interproscan#291]
Hi guys, I need some help, I am getting an error with the `.h3i` format when running the latest version (5.57-90.0). I have tried having only the `.hmm` files, and also hmm-pressing them before, so using the `.h3m` and `.h3i`, but always getting similar errors.
Pasting one below, but it's happening with all Databases.

This is running in Python3.7.

Any help is welcomed, happy to try anything as I have already run out of ideas.
tks!!

```
ip-172-60-32-13.ec2.internal_20221003_132111953_5mrc//jobTIGRFAM/000000000001_000000000492.raw.out /mnt/vol/annotation/dbs/iprscan/tigrfam/15.0/TIGRFAMs_HMM.LIB /mnt/efs/genomes/results/SYM57343/WGS18118/ASM-txvdzN/annotation/ANN-79MFN4JTs/iprscan_975/temp/ip-172-60-32-13.ec2.internal_20221003_132111953_5mrc//jobTIGRFAM/000000000001_000000000492.fasta 
Error output from binary:

Error: File format problem in trying to open HMM file /mnt/vol/annotation/dbs/iprscan/tigrfam/15.0/TIGRFAMs_HMM.LIB.
Opened /mnt/vol/annotation/dbs/iprscan/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3m, a pressed HMM file; but format of its .h3i file unrec


	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-10-03 13:28:05,028 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepTIGRFAMRunHmmer3
2022-10-03 13:28:05,103 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 49 : Run fingerprintscan Binary for selected proteins for proteins 1 to 492 has failed irretrievably.  Available StackTraces follow.
2022-10-03 13:28:05,103 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2022-10-03 13:28:05,103 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:349] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167) [interproscan-5.jar:?]
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:488) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:167)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:488)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```

**Comment by tgrego** [comment]
I'm not sure what is happening... did you use the initial_setup.py script for the hmm-pressing?
please debug one member database at a time (using the -appl flag) as it can be difficult to track multiple member database failures.
