### ISSUE TITLE
which java version? Incompatible magic value 4294967295 in class file 

### ISSUE THREAD

**Issue by ejblom** [ebi-pf-team/interproscan#299]
Hi

I am trying to run InterProscan in a Docker container. I tried with the latest openjdk-11 image, which is the minimum Java requirement. I was getting these errors:
```
Exception in thread "Thread-0" java.lang.ClassFormatError: Incompatible magic value 4294967295 in class file java/util/WeakHashMap$KeyIterator
        at java.base/java.util.WeakHashMap$KeySet.iterator(WeakHashMap.java:880)
        at org.h2.engine.OnExitDatabaseCloser.onShutdown(OnExitDatabaseCloser.java:83)
        at org.h2.engine.OnExitDatabaseCloser.run(OnExitDatabaseCloser.java:114)
```
so I decided to go with an ubuntu 20.04 base image and install openjdk 17 (the latest LTS version). However for 100 analyses, around
30-40 get this error. Is there a specific Java JDK used? Or perhaps some other suggestions?

**Comment by matthiasblum** [comment]
Works fine with OpenJDK 17:
