### ISSUE TITLE
Error during the InterProScan test run

### ISSUE THREAD

**Issue by ChongLC** [ebi-pf-team/interproscan#304]
Dear developer, 

I am trying the interproscan installation from this document - [https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html](https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html). All steps are fine with no error. 

While running interproscan with this command `./interproscan.sh`, it nicely executes the usage instructions. However, while running the test run `python3 initial_setup.py`, I got this error: 
```
python3: can't open file 'initial_setup.py': [Errno 2] No such file or directory
```

The error is due to there is no `initial_setup.py` in the respective folder. Here, I listed all the folders and files from my interproscan folder: 
```
drwxrwsr-x  7 chong chong     22 Dec  8 16:46 ./
drwxrwxrwx  3 chong chong      5 Jan 24 16:24 ../
drwxrwsr-x 19 chong chong     19 Dec  8 16:12 bin/
drwxrwsr-x 19 chong chong     19 Dec  8 16:46 data/
-rwxrwxrwx  1 chong chong 370258 Dec  8 16:11 interproscan-5.jar*
-rwxrwxrwx  1 chong chong   7377 Dec  8 16:09 interproscan.properties*
-rwxrwxrwx  1 chong chong   1686 Dec  8 16:09 interproscan.sh*
drwxrwsr-x  2 chong chong    139 Dec  8 16:12 lib/
-rwxrwxrwx  1 chong chong    142 Dec  8 16:09 readme.txt*
-rwxrwxrwx  1 chong chong   2956 Dec  8 16:09 setup.py*
drwxrwxr-x  5 chong chong      5 Dec  8 16:09 src/
-rwxrwxrwx  1 chong chong   4114 Dec  8 16:09 test_all_appl.fasta*
-rwxrwxrwx  1 chong chong  62790 Dec  8 16:09 test_convert_mode.xml*
-rwxrwxrwx  1 chong chong   6582 Dec  8 16:09 test_nt_redundant.fasta*
-rwxrwxrwx  1 chong chong 209859 Dec  8 16:09 test_nt_seqs_convert_mode.xml*
-rwxrwxrwx  1 chong chong   5396 Dec  8 16:09 test_nt_seqs.fasta*
-rwxrwxrwx  1 chong chong  84138 Dec  8 16:09 test_proteins_convert_mode.xml*
-rwxrwxrwx  1 chong chong   1685 Dec  8 16:09 test_proteins.fasta*
-rwxrwxrwx  1 chong chong   1649 Dec  8 16:09 test_proteins_new.fasta*
-rwxrwxrwx  1 chong chong   4259 Dec  8 16:09 test_proteins_redundant.fasta*
-rwxrwxrwx  1 chong chong    272 Dec  8 16:09 test_single_protein.fasta*
drwxrwxr-x  6 chong chong      6 Dec  8 16:09 work/
```

May I know how to tackle this issue? 

Best regards, 
Chong

**Comment by tgrego** [comment]
Hi Chong,
you should run `python3 setup.py interproscan.properties` instead. initial_setup.py has been removed.

**Comment by ChongLC** [comment]
Hi @tgrego, 
I have run `python3 setup.py interproscan.properties` after running `tar -pxvzf interproscan-5.60-92.0-*-bit.tar.gz`. 

This is the list of the command that I ran: 
```
mkdir interproscan
cd interproscan/
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.60-92.0/interproscan-5.60-92.0-64-bit.tar.gz
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.60-92.0/interproscan-5.60-92.0-64-bit.tar.gz.md5
md5sum -c interproscan-5.60-92.0-64-bit.tar.gz.md5
tar -pxvzf interproscan-5.60-92.0-*-bit.tar.gz
cd interproscan-5.60-92.0/
python3 setup.py interproscan.properties
./interproscan.sh
```

However, I got an error while running the test with this command: 
```
./interproscan.sh -i test_all_appl.fasta -f tsv -dp
```

Error: 
```
25/01/2023 09:52:18:718 Welcome to InterProScan-5.60-92.0
25/01/2023 09:52:18:719 Running InterProScan v5 in STANDALONE mode... on Linux
25/01/2023 09:52:24:060 RunID: infinitum_20230125_095223672_5m8g
25/01/2023 09:52:34:819 Loading file /mnt/twincore/compvironas/software/interproscan/interproscan-5.60-92.0/test_all_appl.fasta
25/01/2023 09:52:34:821 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2021_04,MobiDBLite-2.0,PANTHER-17.0,Pfam-35.0,PIRSF-3.10,PIRSR-2021_05,PRINTS-42.0,ProSitePatterns-2022_01,ProSiteProfiles-2022_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2023-01-25 09:52:41,321 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: python3 bin/prosite/runprosite.py data/prosite/2022_01/profile_models /mnt/twincore/compvironas/software/interproscan/interproscan-5.60-92.0/temp/infinitum_20230125_095223672_5m8g//jobPrositeProfiles/000000000001_000000000006.fasta /mnt/twincore/compvironas/software/interproscan/interproscan-5.60-92.0/temp/infinitum_20230125_095223672_5m8g//jobPrositeProfiles/000000000001_000000000006.raw.out bin/prosite/pfsearchV3 -f -o 7 -t 4
Error output from binary:
bin/prosite/pfsearchV3: error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory
Error running prosite binary bin/prosite/pfsearchV3

2023-01-25 09:52:41,326 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: python3 bin/prosite/runprosite.py data/prosite/2022_01/profile_models /mnt/twincore/compvironas/software/interproscan/interproscan-5.60-92.0/temp/infinitum_20230125_095223672_5m8g//jobPrositeProfiles/000000000001_000000000006.fasta /mnt/twincore/compvironas/software/interproscan/interproscan-5.60-92.0/temp/infinitum_20230125_095223672_5m8g//jobPrositeProfiles/000000000001_000000000006.raw.out bin/prosite/pfsearchV3 -f -o 7 -t 4
Error output from binary:
bin/prosite/pfsearchV3: error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory
Error running prosite binary bin/prosite/pfsearchV3

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201) ~[interproscan-management-5.60-92.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073) [spring-jms-5.2.22.RELEASE.jar:5.2.22.RELEASE]
        at java.lang.Thread.run(Thread.java:829) [?:?]
...
```
As the error message is quite long, I shared a [text file](https://drive.google.com/file/d/1JiceCUe4fVPc5idcGcB4kSAVaIdy6DOl/view?usp=share_link) of the entire error message. 

Looking forward to hearing a solution from you. 

Thank you. 

Best regards, 
Chong

**Comment by ChongLC** [comment]
Dear @tgrego, 

I solved the issue with `sudo apt-get install libpcre3 libpcre3-dev`. I will then close the issue. Thank you. 

Best regards, 
Chong
