### ISSUE TITLE
Error setting affinity!

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ebi-pf-team/interproscan#306]
Running interproscan gives me this error:

interproscan.sh -i /g/data/nm31/d/r17_nepenthes/r17.2_synteny/ptg000074l_genes.faa -b /g/data/nm31/d/r17_nepenthes/r17.2_synteny/interpro/ptg000074l -dp -goterms -pa -T ./ -dra 

Loading python3/3.9.2
  Loading requirement: intel-mkl/2020.3.304
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl -d data/prosite/2022_01/prosite_patterns.dat --pfscan /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 -b data/prosite/2022_01/evaluator.dat -r -s -o ipro /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositePatterns/000000000001_000000001931.fasta 
Error output from binary:
Error setting affinity!
Could not execute /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 --matrix-only -o4 -L-1 /jobfs/70934125.gadi-pbs/ps1024874-1.tmp /jobfs/70934125.gadi-pbs/ps1024874-3.tmp  > /jobfs/70934125.gadi-pbs/ps1024874-2.tmp: Inappropriate ioctl for device at /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl line 1751.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: python3 /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/runprosite.py data/prosite/2022_01/profile_models /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositeProfiles/000000001001_000000001931.fasta /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositeProfiles/000000001001_000000001931.raw.out /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfsearchV3 -f -o 7 -t 4 
Error output from binary:
Error setting affinity!
Error running prosite binary /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfsearchV3

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl -d data/prosite/2022_01/prosite_patterns.dat --pfscan /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 -b data/prosite/2022_01/evaluator.dat -r -s -o ipro /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositePatterns/000000000001_000000001931.fasta 
Error output from binary:
Error setting affinity!
Could not execute /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 --matrix-only -o4 -L-1 /jobfs/70934125.gadi-pbs/ps913816-1.tmp /jobfs/70934125.gadi-pbs/ps913816-3.tmp  > /jobfs/70934125.gadi-pbs/ps913816-2.tmp: Inappropriate ioctl for device at /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl line 1751.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: python3 /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/runprosite.py data/prosite/2022_01/profile_models /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositeProfiles/000000001001_000000001931.fasta /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositeProfiles/000000001001_000000001931.raw.out /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfsearchV3 -f -o 7 -t 4 
Error output from binary:
Error setting affinity!
Error running prosite binary /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfsearchV3

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl -d data/prosite/2022_01/prosite_patterns.dat --pfscan /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 -b data/prosite/2022_01/evaluator.dat -r -s -o ipro /jobfs/70934125.gadi-pbs/./gadi-cpu-clx-0043.gadi.nci.org.au_20230127_142257945_3ui2//jobPrositePatterns/000000000001_000000001931.fasta 
Error output from binary:
Error setting affinity!
Could not execute /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/pfscanV3 --matrix-only -o4 -L-1 /jobfs/70934125.gadi-pbs/ps1021223-1.tmp /jobfs/70934125.gadi-pbs/ps1021223-3.tmp  > /jobfs/70934125.gadi-pbs/ps1021223-2.tmp: Inappropriate ioctl for device at /g/data/nm31/bin/interproscan/interproscan-5.60-92.0/bin//prosite/ps_scan.pl line 1751.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:169)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by tgrego** [comment]
Hello,
the included default binaries use affinity which your system does not seem to support.
You can try the included alternative binaries compiled without affinity support, but its possible those will not work on your system so you might have to compile the binaries.
Please refer to https://interproscan-docs.readthedocs.io/en/latest/KnownIssues.html#prosite-pfsearchv3-errors
