### ISSUE TITLE
Error reported with fingerPRINTScan on test data following conda install

### ISSUE THREAD

**Issue by TMAdams** [ebi-pf-team/interproscan#312]
Dear interproscan team,

I've attempted to install interproscan 5.59_91.0 (latest version on conda) on Rocky Linux version 8.7 with conda version 23.1.0. I followed the install instructions in your documentation, except for using the solution in #305 to get past the error reported by hmmpress. I'm receiving the following error message when run on the provided test data with and without pre-calc enabled:

2023-03-07 17:37:22,633 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.IllegalStateException: Command line failed with exit code: 139
Command: bin/prints/fingerPRINTScan data/prints/42.0/prints.pval /mnt/shared/scratch/tadams/apps/conda/envs/interproscan/share/InterProScan/temp/n19-32-192-crossbones.hpc.hutton.ac.uk_20230307_173443457_hzhj//jobPRINTS-42.0/000000000001_000000000006.fasta -e 0.0001 -d 10 -E 257043 84355444 -fj -o 15
Error output from binary:

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87)
        at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-07 17:37:22,634 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrintsRunFingerPrintScan
2023-03-07 17:37:22,749 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 61 : Run fingerprintscan Binary for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2023-03-07 17:37:22,749 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2023-03-07 17:37:22,750 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:363] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:169) [interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:169)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

I haven't seen mention elsewhere of an issue with this specific binary, trying to run it in isolation just reports a segmentation fault.

Version 5.55 installs fine after using the workaround of using an old version of hmmpress to get past the same error with the hmms.

I'd appreciate any assistance you can provide and can provide more information if needed.

**Comment by matthiasblum** [comment]
Well, two years late (sorry!)...

1. We are not maintaining the Conda package, and I'd recommend against using it.
2. We have a Docker image, which greatly simply things: https://hub.docker.com/r/interpro/interproscan
3. In recent releases, we ship the data with the "hmmpressed" files, so it is no longer necessary to run `hmmpress` before running InterProScan for the first time.
