### ISSUE TITLE
FATAL - Analysis step 73 : Parse output from HMMER3 and CathResolveHits has failed

### ISSUE THREAD

**Issue by Timothy-Amos** [ebi-pf-team/interproscan#32]
Hi,

I can run InterProScan (v5.25-64.0) on the test file test_proteins.fasta but I get an error when I try to use my own data.

Any suggestions on what went wrong?

I used the command:

`interproscan.sh -i rhiMar2.2.all.maker.proteins.head100.fasta -f xml -goterms -iprlookup -T $TMPDIR > rhiMar2.2.all.maker.proteins.head100.interpro.out`

My input file looks like this:

```
[z3101118@kdm subset.2017-08-03]$ head rhiMar2.2.all.maker.proteins.head100.fasta
>maker-ctg29523_RHIMB__RM170330.29523-snap-gene-0.0-mRNA-1 protein AED:0.08 eAED:0.31 QI:100|0|0|1|0|0|2|0|194
MHSTTCVSQDQGMNSATAGMMWPDWGYCPKEGQERVDRQGLSLSSRVTLAVKGNCIPTQF
TKSRCQTLILTVTNSQLTDIDLYVLGRYTPQGSQMPIFQLYWKSFENKSKPFEATPSPDD
INLLLPSQYDLIARAPYTMQKTLAVETGFSDHNLWLEWASYIASQMNRTGCITCAPAQPH
LGTMYKYICQSDGQ
>snap_masked-ctg3453_RHIMB__RM170330.3453-processed-gene-0.3-mRNA-1 protein AED:0.04 eAED:0.04 QI:740|1|0.88|1|0.37|0.66|9|0|127
MRPQQQDIERPFLPQQRPQLHWKENTAENEENEAIHKTFNYFLEFVPTNDIERFVRELGL
TNNEINWAKHDNIGTYNQHYSMLLKLQQDRKFDVNIWLNKLYDIKMGEVAQKITEKLTRD
GLCETST
>maker-ctg3453_RHIMB__RM170330.3453-snap-gene-0.12-mRNA-1 protein AED:0.06 eAED:0.07 QI:0|0|0|1|0.33|0|4|0|431
```

And got this error:

```
[z3101118@kdm subset.2017-08-03]$ cat rhiMar2.2.all.maker.proteins.head100.interpro.out
03/08/2017 13:02:45:106 Welcome to InterProScan-5.25-64.0
03/08/2017 13:02:51:575 Running InterProScan v5 in STANDALONE mode... on Linux
03/08/2017 13:03:04:858 Loading file /srv/scratch/z3101118/WhiteP.CaneToad-Jan16/analysis/2017-08-03.interproscan/subset.2017-08-03/rhiMar2.2.all.maker.proteins.head100.fasta
03/08/2017 13:03:04:861 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.1.0,Hamap-201701.18,MobiDBLite-1.0,PANTHER-11.1,Pfam-31.0,Phobius-1.01,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-20.132,ProSiteProfiles-20.132,SFLD-2,SignalP_EUK-4.1,SignalP_GRAM_NEGATIVE-4.1,SignalP_GRAM_POSITIVE-4.1,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0,TMHMM-2.0c]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
03/08/2017 13:03:22:929 26% completed
2017-08-03 13:03:47,209 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NumberFormatException: For input string: "by"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolverRecord.valueOf(CathResolverRecord.java:106)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolveHitsOutputParser.parse(CathResolveHitsOutputParser.java:40)
	at uk.ac.ebi.interpro.scan.management.model.implementations.gene3d.Gene3DParseAndPersistOutputStep.execute(Gene3DParseAndPersistOutputStep.java:115)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-08-03 13:03:47,212 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepGene3dParseOutputs
2017-08-03 13:03:47,226 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 73 is being re-run following a failure.
2017-08-03 13:03:47,230 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NumberFormatException: For input string: "by"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolverRecord.valueOf(CathResolverRecord.java:106)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolveHitsOutputParser.parse(CathResolveHitsOutputParser.java:40)
	at uk.ac.ebi.interpro.scan.management.model.implementations.gene3d.Gene3DParseAndPersistOutputStep.execute(Gene3DParseAndPersistOutputStep.java:115)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-08-03 13:03:47,231 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepGene3dParseOutputs
2017-08-03 13:03:47,359 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 73 is being re-run following a failure.
2017-08-03 13:03:47,362 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.NumberFormatException: For input string: "by"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolverRecord.valueOf(CathResolverRecord.java:106)
	at uk.ac.ebi.interpro.scan.io.gene3d.CathResolveHitsOutputParser.parse(CathResolveHitsOutputParser.java:40)
	at uk.ac.ebi.interpro.scan.management.model.implementations.gene3d.Gene3DParseAndPersistOutputStep.execute(Gene3DParseAndPersistOutputStep.java:115)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-08-03 13:03:47,362 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepGene3dParseOutputs
2017-08-03 13:03:47,481 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 73 : Parse output from HMMER3 and CathResolveHits for proteins 1 to 12 has failed irretrievably.  Available StackTraces follow.
2017-08-03 13:03:47,481 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2017-08-03 13:03:47,481 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:241] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:128)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:375)
```

Thanks,

Tim

**Comment by Timothy-Amos** [comment]
In the example above, I had accidentally truncated one of my protein sequences but I don't think this is the problem. I also tried renaming my fasta headers but I also don't think that that is the problem. I tried increasing and decreasing the number of sequences too. I also tried simplifying the program options to no avail. 

Across my various attempts I seem to get two failure modes:

The previously mentioned "Parse output from HMMER3 and CathResolveHits ... has failed":

```
[z3101118@kdm subset.2017-08-03]$ grep FATAL rhiMar2.2.all.maker.proteins.head100.interpro.out -m 1
2017-08-03 13:03:47,481 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 73 : Parse output from HMMER3 and CathResolveHits for proteins 1 to 12 has failed irretrievably.  Available StackTraces follow.
```

and a "Run pfsearch for selected proteins ... has failed" one:

```
[z3101118@kdm subset.2017-08-03]$ grep FATAL rhiMar2.2.all.maker.proteins.head84.rename.interpro.out -m 1
2017-08-04 13:11:06,067 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 16 : Run pfsearch for selected proteins for proteins 1 to 11 has failed irretrievably.  Available StackTraces follow.
```

I'm guessing that the step number isn't relevant because it doesn't seem to vary predictably across attempts.

Note that the command I used with the test data was otherwise identical to original one that didn't work:

`interproscan.sh -i /share/apps/interproscan/5.25-64.0/test_proteins.fasta -f xml -goterms -iprlookup -T $TMPDIR > test_proteins.interpro.out`

**Comment by gsn7** [comment]
send us the input sequences you used so that we can reproduce this. You can send them as a zipped file to interhelp@ebi.ac.uk

**Comment by gsn7** [comment]
or you can attach the sequence file here

**Comment by gsn7** [comment]
the input sequence set run successfully, so it is possible the problem has to do with your $TMPDIR. change the following property in interproscan.properties file from 
delete.temporary.directory.on.completion=true
to 
delete.temporary.directory.on.completion=false

then issue the command as before with option '-T $TMPDIR/testipr'
interproscan.sh -i rhiMar2.2.all.maker.proteins.head100.fasta -f xml -goterms -iprlookup -T $TMPDIR/testipr > rhiMar2.2.all.maker.proteins.head100.interpro.out

If it fails, zip the directory $TMPDIR/testipr and send it to us.

**Comment by Timothy-Amos** [comment]
Local IT support managed to fix the problem.

They installed https://github.com/UCLOrengoGroup/cath-tools/releases/download/v0.12.26/cath-resolve-hits.centos6 to solve the CathResolveHits error (as described at https://github.com/ebi-pf-team/interproscan/wiki/KnownIssues) and they told me to load the python v2.7.12 module to fix the pfsearch error.

Thanks for your help.
