### ISSUE TITLE
interproscan not recognizing fasta format 

### ISSUE THREAD

**Issue by amsamani** [ebi-pf-team/interproscan#333]
Hi,

I think interproscan is giving me error because it cannot recognize fasta format of input file.

here is part of my error

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2023-08-25 13:30:55,758 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalArgumentException: 'sequence' is not an amino acid sequence [ICPVCKRSIALRRPVQIMQLRPTRMARSTAQRS.TLTTPS.PWT.AVPKSLPLPPPPFPASAPLWRVTLAAMISSLPASTKCNLPPPARGPS.RWKTHGSPRTSPHCHPPQTRGCPAPPCTSSNLHPPRPPHLASPLTRACGTSPRCSPHRAACRPAT.WTLPP.RPCLPASPSSTSSPRPPTRRPRLPTCATTLPP.ACPWAPTGQPPASHTWRAIPTGCTWPKDQPP.PSHRSASTQPPPA.WGRAAAAAAVASRPHPAGAPRLGKAPAPSAGTMPPASTTGYGRARAARAFSREQFRKMQNMFVWQIKTVQWTRDVVTDANTAGSRSVSVSAWLKKLSVLTA.KGEEVVCLPNQRAPYSKNPLSPPHLLLLST..TPLYEL.PTPRPGSLTIQDTVPPIRLLQAQMQNMYNSSIIF.LPPLT.PEAGQKKSQDLLTSQKKIRHYS.SQLFWSCLY.DSPSGLILLRISLYSAMDLCFIDFSAFEDLGSGSTLLKTFP.T.RALTLISQP.QVYQL.L.LQQNDMD.KNQRKWKSYATRSQAV.KIT.LSVAKTKDNRLSLQSRRYWVFWLTCVLSAHWDCSASFT.NWKTWCQPLPLSTGCFWTPYPS]
	at uk.ac.ebi.interpro.scan.model.Protein.setSequence(Protein.java:343) ~[interproscan-model-5.63-95.0.jar:?]
	at uk.ac.ebi.interpro.scan.model.Protein.setSequenceAndMd5(Protein.java:227) ~[interproscan-model-5.63-95.0.jar:?]
	at uk.ac.ebi.interpro.scan.model.Protein.<init>(Protein.java:134) ~[interproscan-model-5.63-95.0.jar:?]
	at uk.ac.ebi.interpro.scan.business.sequence.fasta.LoadFastaFileIntoDBImpl.addToMoleculeCollectionInDB(LoadFastaFileIntoDBImpl.java:314) ~[interproscan-business-5.63-95.0.jar:?]
	at uk.ac.ebi.interpro.scan.business.sequence.fasta.LoadFastaFileIntoDBImpl.loadSequences(LoadFastaFileIntoDBImpl.java:149) ~[interproscan-business-5.63-95.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]

Here is a line of my fasta file.

>CLIV3_000104-RA
AWEINILELMVYACGNTSVLPSGAGDCYGANPDFSLCSQVLVG
WAVGGESYQFPNEAGISIGTLRDPQYIQLEIHYSNFDLLPDSSGMRIYHMPELRKYDVGVLQTGVFI
FPVHFIPPGAESYRSYGLCNSSQFDEM

**Comment by matthiasblum** [comment]
Hi @amsamani,

Is it possible that your input sequence is missing the greater-than character (`>`)? The first line (description/name of the sequence) must begins with this character.

```
>CLIV3_000104-RA
AWEINILELMVYACGNTSVLPSGAGDCYGANPDFSLCSQVLVG
WAVGGESYQFPNEAGISIGTLRDPQYIQLEIHYSNFDLLPDSSGMRIYHMPELRKYDVGVLQTGVFI
FPVHFIPPGAESYRSYGLCNSSQFDEM
```
