### ISSUE TITLE
rpsblast not working, libgnutls.so.28: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bastian-wur** [ebi-pf-team/interproscan#35]
Hi everyone :).

I just downloaded the latest version of Interproscan, 5.26-65.0 , and it seems that the ncbi-blast-2.6.0+/rpsblast is not working.
The system throws the following error during execution:

```
2017-10-05 12:40:49,595 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /exports/mm-hpc/bacteriologie/bastian/data/metronidazol_resistance_new/HKF5JBBXX_103099-001-025_assembly/ray_run141/opera/ray.gapfiller/annotationHKF5JBBXX_103099-001-025//temp/weaselshark_20171005_115510659_fx2d//jobCDD/000000002001_000000003000.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

2017-10-05 12:40:49,598 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /exports/mm-hpc/bacteriologie/bastian/data/metronidazol_resistance_new/HKF5JBBXX_103099-001-025_assembly/ray_run141/opera/ray.gapfiller/annotationHKF5JBBXX_103099-001-025//temp/weaselshark_20171005_115510659_fx2d//jobCDD/000000002001_000000003000.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2017-10-05 12:40:49,600 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepCDDRunBinaryRPSblast
2017-10-05 12:40:49,692 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 101 is being re-run following a failure.
```

No clue what's happening here.
I think I already had the same problem with the previous version, where I just replaced the binary with a working version, but thought I should report it back.

This happens on Ubuntu 14.04.5 LTS, the whole thing is executed on a HPC cluster.

Unrelated to the bug report: Thanks guys for the good work, my daily work would be harder without this tool :).

**Comment by diecasfranco** [comment]
Hi, I have the same problem:
2017-10-05 11:22:43,178 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: /home/dfranco/interproscan/interproscan-5.25-64.0/bin/blast/ncbi-blast-2.6.0+/rpsblast -query /home/dfranco/analise_metagenoma/anvio_results/HR4/temp/seal_20171004_104055397_hqhj//jobCDD/000000004001_000000005000.fasta -db /home/dfranco/interproscan/interproscan-5.25-64.0/data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
/home/dfranco/interproscan/interproscan-5.25-64.0/bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
2017-10-05 11:22:43,178 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepCDDRunBinaryRPSblast
2017-10-05 11:22:56,716 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 26417 is being re-run following a failure

**Comment by gisleDK** [comment]
Just install the GNU TLS library.
For Ubuntu you can find it here:
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libgnutls&searchon=names
Or don't bother and just do
sudo apt-get install libgnutls28

**Comment by gsn7** [comment]
the cdd/rpsblast binaries bundled with interproscan were compiled on redhat7. if they don't work  try the binaries provided at ncbi or follow the instructions provided here https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#cdds-rpsblastrpsbproc to compile for your platform.
or as @gisleDK suggests it may also be that you just need to update GNU TLS library.

**Comment by tyyl622** [comment]
I have been solved by one of the developers of the software helping me. Pay attention that your whole system python version should be 2.7. 
Just as (https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#cdds-rpsblastrpsbproc)  says that:
First check the c++ compiler version
`c++ --version`
if the c++ version is less than 4.8 compilation will most likely fail and you should upgrade to a c++ compiler version 4.8 or above.
If you have a c++ version 4.8 or above then follow the instructions below.
```
mkdircddblast
cd cddblast
wget ftp://ftp.ncbi.nih.gov/blast/executables/LATEST/ncbi-blast-2.6.0+-src.tar.gz
wget ftp://ftp.ncbi.nih.gov/blast/executables/LATEST/ncbi-blast-2.6.0+-src.tar.gz.md5
md5sum -c ncbi-blast-2.6.0+-src.tar.gz.md5
#Above command should return "ncbi-blast-2.6.0+-src.tar.gz: OK" if download successful
tar xvzf ncbi-blast-2.6.0+-src.tar.gz
cd ncbi-blast-2.6.0+-src/c++/src/app/
wget -r --no-parent -l 1 -np -nd -nH -P rpsbproc ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/
#edit Makefile.in and make sure SUB_PROJ is assigned two applications as follows: SUB_PROJ = blast rpsbproc. 
#Note that you only edit one Makefile.in, which is ncbi-blast-2.6.0+-src/c++/src/app/Makefile.in, and don't add SUB_PROJ = blast rpsbproc directly, you should type ' \' at the end of the pre-existing words in the Makefile.in and then add blast rpsbproc  on the new line 
#Then you do:
cd ../../
./configure
/usr/bin/make
#after compilation is complete
cp ReleaseMT/bin/rpsblast <interproscan_install_dir>/bin/blast/ncbi-blast-2.6.0+/
cp ReleaseMT/bin/rpsbproc <interproscan_install_dir>/bin/blast/ncbi-blast-2.6.0+/
```
And rerun the interprosan as instructions, it works out.
