### ISSUE TITLE
Need help installing interproscan on a server with multiple users

### ISSUE THREAD

**Issue by lwebercoralgirl** [ebi-pf-team/interproscan#36]
Hello,

I would like to install interproscan on a server that is used by multiple users. 
Do you have any advice for doing this (i.e. modifying the properties file to point to the path where specific files and libraries are stored)?

I tried to run the interproscan test but received this error message:

For the (-u) option you specified a location which is not writable:
/usr/local/interproscan/interproscan-5.26-65.0/test_proteins.fasta

Thanks!

**Comment by gsn7** [comment]
you can install interproscan anywhere, but it requires that the current working directory when running it, to be writable and the default current working directory is $PWD
the following should work:
cd /home/username
/usr/local/interproscan/interproscan-5.26-65.0/interproscan.sh -i /usr/local/interproscan/interproscan-5.26-65.0/test_all_appl.fasta -b output_results_test_all

**Comment by lwebercoralgirl** [comment]
Thanks for your help!

I just tried to run this and I got the following error (I replaced my account information with xxxx's):

ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/3/sfld_sites.annot -a /home/xxxxxxxxxxx//jobSFLD/000000000001_000000000004.raw.align.out -O /home/xxxxxxxxxxxx_20171013_071406694_7qd3//jobSFLD/000000000001_000000000004.raw.out -d /home/xxxxxxxxxxxxxxx_20171013_071406694_7qd3//jobSFLD/000000000001_000000000004.raw.domtblout.out -o /home/xxxxxxxxxxxxxxxx_20171013_071406694_7qd3//jobSFLD/000000000001_000000000004_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2017-10-13 07:14:34,452 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2017-10-13 07:14:34,475 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 9 : Run sfld postprocessing binary for selected proteins for proteins 1 to 4 has failed irretrievably.  Available StackTraces follow.
2017-10-13 07:14:34,476 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2017-10-13 07:14:34,476 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:241] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:128)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by gsn7** [comment]
you are most likely running on an older linux system. check the first issue under:
https://github.com/ebi-pf-team/interproscan/wiki/KnownIssues#1-cddrpsblast-gene3d-and-sfld-errors-on-older-or-new-systems

**Comment by tyyl622** [comment]
I had the same problems as you but now it have been solved by one of the developers of the software helping me. Pay attention that your whole system python version should be 2.7. 
Just as (https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#cdds-rpsblastrpsbproc)  says that:
First check the c++ compiler version
`c++ --version`
if the c++ version is less than 4.8 compilation will most likely fail and you should upgrade to a c++ compiler version 4.8 or above.
If you have a c++ version 4.8 or above then follow the instructions below.
```
mkdircddblast
cd cddblast
wget ftp://ftp.ncbi.nih.gov/blast/executables/LATEST/ncbi-blast-2.6.0+-src.tar.gz
wget ftp://ftp.ncbi.nih.gov/blast/executables/LATEST/ncbi-blast-2.6.0+-src.tar.gz.md5
md5sum -c ncbi-blast-2.6.0+-src.tar.gz.md5
#Above command should return "ncbi-blast-2.6.0+-src.tar.gz: OK" if download successful
tar xvzf ncbi-blast-2.6.0+-src.tar.gz
cd ncbi-blast-2.6.0+-src/c++/src/app/
wget -r --no-parent -l 1 -np -nd -nH -P rpsbproc ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/
#edit Makefile.in and make sure SUB_PROJ is assigned two applications as follows: SUB_PROJ = blast rpsbproc. 
#Note that you only edit one Makefile.in, which is ncbi-blast-2.6.0+-src/c++/src/app/Makefile.in, and don't add SUB_PROJ = blast rpsbproc directly, you should type ' \' at the end of the pre-existing words in the Makefile.in and then add blast rpsbproc  on the new line 
#Then you do:
cd ../../
./configure
/usr/bin/make
#after compilation is complete
cp ReleaseMT/bin/rpsblast <interproscan_install_dir>/bin/blast/ncbi-blast-2.6.0+/
cp ReleaseMT/bin/rpsbproc <interproscan_install_dir>/bin/blast/ncbi-blast-2.6.0+/
```
And rerun the interprosan as instructions you will find it works out.

**Comment by kbvstmd** [comment]
All of your questions can be found here.     https://qiita.com/okuman/items/73bebfd711d3f955c167
