### ISSUE TITLE
runs test data but fails on my data

### ISSUE THREAD

**Issue by juliayork** [ebi-pf-team/interproscan#369]
I saw this issue previously and tried installing elfutils, but the same error occurs. 

2024-06-16 16:38:54,893 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepLoadFromFastaIntoDB
2024-06-16 16:38:55,004 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 1 : Load proteins from a fasta file and load into DB before creating required JobInstance objects for proteins null to null has failed irretrievably.  Available StackTraces follow.
2024-06-16 16:38:55,004 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2024-06-16 16:38:55,004 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:363] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:169) [interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:169)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413)

**Comment by tgrego** [comment]
Hello, if the provided test fasta files work it's likely interproscan is working properly and the issue is with your input fasta file. Can you please double check your input fasta file is formed correctly?
You can also just test with a small subsection of your file (a few sequences only) to make it easier to find possible issues with the file or interproscan.
Thank you

**Comment by matthiasblum** [comment]
Please post the full error log.
