### ISSUE TITLE
HMM error whilst running test data 

### ISSUE THREAD

**Issue by stxjf7** [ebi-pf-team/interproscan#375]
Whilst testing the program intallation with the test data commands:
_./interproscan.sh -i test_all_appl.fasta -f tsv -dp
./interproscan.sh -i test_all_appl.fasta -f tsv_

I am encountering the error below. 
I have already attempted to reindex the files with: _python3 setup.py -f interproscan.properties_
I can see data/ncbifam/15.0/ncbifam.hmm exists with file size 1069618bytes

Any suggestions on what else to try please?

**edit**
I am also getting errors for 
cannot open input file data/prints/42.0/prints.pval
HMM file data/antifam/7.0/AntiFam.hmm.
HMM file data/gene3d/4.3.0/gene3d_main.hmm not found 
.... and several other files in data/.
*********

 

07/08/2024 10:31:53:309 Welcome to InterProScan-5.62-94.0
07/08/2024 10:31:53:310 Running InterProScan v5 in STANDALONE mode... on Linux
07/08/2024 10:31:57:864 RunID: comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk
07/08/2024 10:32:05:488 Loading file /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/test_all_appl.fasta
07/08/2024 10:32:05:489 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_01,MobiDBLite-2.0,NCBIfam-11.0,Pfam-35.0,PIRSF-3.10,PIRSR-2021_05,PRINTS-42.0,ProSitePatterns-2022_05,ProSiteProfiles-2022_05,SFLD-4,SMART-9.0,SUPERFAMILY-1.75]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2024-08-07 10:32:11,378 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 15364 --cut_tc --cpu 1 -o /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.raw.out data/ncbifam/11.0/ncbifam.hmm /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.fasta 
Error output from binary:

Error: File existence/permissions problem in trying to open HMM file data/ncbifam/11.0/ncbifam.hmm.
HMM file data/ncbifam/11.0/ncbifam.hmm not found (nor an .h3m binary of it)

2024-08-07 10:32:11,383 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 15364 --cut_tc --cpu 1 -o /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.raw.out data/ncbifam/11.0/ncbifam.hmm /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.fasta 
Error output from binary:

Error: File existence/permissions problem in trying to open HMM file data/ncbifam/11.0/ncbifam.hmm.
HMM file data/ncbifam/11.0/ncbifam.hmm not found (nor an .h3m binary of it)

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201) ~[interproscan-management-5.62-94.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2024-08-07 10:32:11,389 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 15364 --cut_tc --cpu 1 -o /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.raw.out data/ncbifam/11.0/ncbifam.hmm /gpfs01/home/stxjf7/misc/interproscan-5.69-101.0/temp/comp009.int.ada.nottingham.ac.uk_20240807_103157708_eunk//jobNCBIfam/000000000001_000000000006.fasta

**Comment by matthiasblum** [comment]
Hi @stxjf7,

You mentioned that `data/ncbifam/15.0/ncbifam.hmm` exists, so I assume you're running InterProScan 5-69.101.0.
However, the error message contains the following:

```
07/08/2024 10:31:53:309 Welcome to InterProScan-5.62-94.0
...
Error: File existence/permissions problem in trying to open HMM file data/ncbifam/11.0/ncbifam.hmm.
HMM file data/ncbifam/11.0/ncbifam.hmm not found (nor an .h3m binary of it)
```

which indicates you're trying to run a much older version of InterProScan. Can you please clarify which version you are running?
