### ISSUE TITLE
Typo in Python Library

### ISSUE THREAD

**Issue by davidbio** [ebi-pf-team/interproscan#381]
I received the following after a fresh install of IPS-5.70-102.0.

```bash
Error output from binary:
Traceback (most recent call last):
  File "bin/mobidb/idrpred-cli.py", line 9, in <module>
    from idrpred.idrpred import main
  File "/home/ips/docker_ips/ips/bin/mobidb/idrpred/__init__.py", line 206, in <module>
    def _repl_struct_by_disord(match: re.Match):
AttributeError: module 're' has no attribute 'Match'
        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201)
```

So I modified `bin/mobidb/idrpred/__init__.py` from

```python
def _repl_struct_by_disord(match: re.Match):
    return _POSITIVE_FLAG * len(match.group(0))
```

to 

```python
def _repl_struct_by_disord(match: re.match):
    return _POSITIVE_FLAG * len(match.group(0))
```

which fixed it for me.

**Comment by matthiasblum** [comment]
Hi @davidbio,

Thank you for reporting this. The `idrpred` package requires Python 3.8 or higher, as `re.Match` is indeed not a valid reference in previous versions of Python.
