### ISSUE TITLE
Remote host terminated the handshake

### ISSUE THREAD

**Issue by qkqk-hub** [ebi-pf-team/interproscan#394]
Hello, I run interproscan with the following code:
`/data_alluser/QK/MAGs/012_interproscan/interproscan-5.65-97.0/interproscan.sh -iprlookup -goterms -f TSV -i eggnog_unannotation_protein_clusts.fasta -o ./interproscan_result/eggnog_unannotation_protein_clusts_all.fasta.ipscan -cpu 40`

The error is as follows:
09/12/2024 08:28:01:491 Welcome to InterProScan-5.65-97.0
09/12/2024 08:28:01:492 Running InterProScan v5 in STANDALONE mode... on Linux
09/12/2024 08:28:09:014 RunID: serverd_20241209_082808704_jj8s
09/12/2024 08:28:28:033 Loading file /data_alluser/QK/Statistical_Analysis/011_protein_COG_picture/eggnog_unannotation_protein_clusts.fasta
09/12/2024 08:28:28:056 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_01,MobiDBLite-2.0,NCBIfam-13.0,PANTHER-18.0,Pfam-36.0,PIRSF-3.10,PIRSR-2023_05,PRINTS-42.0,ProSitePatterns-2022_05,ProSiteProfiles-2022_05,SFLD-4,SMART-9.0,SUPERFAMILY-1.75]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
11/12/2024 18:39:21:054 Uploaded 17217174 unique sequences for analysis
2024-12-11 18:42:21,292 [Thread-6] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:748] WARN - 

The version of InterProScan you are using is 5.65-97.0
The version of the lookup service you are using is 5.72-103.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.

2024-12-11 18:42:21,292 [Thread-8] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:748] WARN - 

The version of InterProScan you are using is 5.65-97.0
The version of the lookup service you are using is 5.72-103.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.

2024-12-11 18:42:21,292 [Thread-7] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:748] WARN - 

The version of InterProScan you are using is 5.65-97.0
The version of the lookup service you are using is 5.72-103.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.

2024-12-11 18:42:21,292 [Thread-9] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:748] WARN - 

The version of InterProScan you are using is 5.65-97.0
The version of the lookup service you are using is 5.72-103.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.

2024-12-11 18:42:21,292 [Thread-10] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:748] WARN - 

The version of InterProScan you are using is 5.65-97.0
The version of the lookup service you are using is 5.72-103.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.

2024-12-11 19:17:18,679 [Thread-22] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
org.apache.http.conn.HttpHostConnectException: Connect to www.ebi.ac.uk:443 [www.ebi.ac.uk/193.62.192.80] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 15 more
2024-12-11 20:21:44,068 [Thread-23] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:819] WARN - lookupUp service at https://www.ebi.ac.uk/interpro/match-lookup is accessible - code: 302,  using proxy: false
2024-12-11 20:21:44,069 [Thread-23] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:713] WARN - Problem with lookup service while on the step: First checking lookup client and server are in sync
2024-12-11 20:21:44,084 [Thread-23] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:715] WARN - 

The following problem was encountered by the pre-calculated match lookup service:
Connect to www.ebi.ac.uk:443 [www.ebi.ac.uk/193.62.192.80] failed: Connection timed out (Connection timed out)
Pre-calculated match lookup service failed - analysis proceeding to run locally
============================================================

The pre-calculated match lookup service has been configured in the interproscan.properties file.  
  precalculated match lookup service url : https://www.ebi.ac.uk/interpro/match-lookup
  precalculated match lookup service proxy host :   proxy port : 3128

Unfortunately the web service has failed. Check the configuration of this service
in the interproscan.properties file and, if necessary, set the following property to look like this:

precalculated.match.lookup.service.url=

If the problem persists, check if this is a firewall or proxy issue. If it is a proxy issue, then setting 
the following property in the interproscan.properties file should work:

precalculated.match.lookup.service.proxy.host=
precalculated.match.lookup.service.proxy.port=

If this still does not work please inform the InterPro team of this error
by sending an email to:

interhelp@ebi.ac.uk

In the meantime, the analysis will continue to run locally.

2024-12-11 20:55:18,733 [Thread-25] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
2024-12-11 20:55:18,731 [Thread-21] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
2024-12-11 20:55:18,731 [Thread-36] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
2024-12-11 20:55:18,731 [Thread-38] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
2024-12-11 20:55:18,735 [Thread-24] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
2024-12-11 20:55:18,737 [Thread-29] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:381] ERROR - Lookup version check failed ... interproscanVersion: 5.65-97.0:vs Lookup version: 
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at uk.ac.ebi.interpro.scan.precalc.client.MatchHttpClient.getServerVersion(MatchHttpClient.java:460)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.getPrecalculated(BerkeleyPrecalculatedProteinLookup.java:366)
        at uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup.run(BerkeleyPrecalculatedProteinLookup.java:158)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 20 more
2024-12-11 20:55:19,566 [Thread-8] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:819] WARN - lookupUp service at https://www.ebi.ac.uk/interpro/match-lookup is accessible - code: 302,  using proxy: false
2024-12-11 20:55:19,567 [Thread-13] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:819] WARN - lookupUp service at https://www.ebi.ac.uk/interpro/match-lookup is accessible - code: 302,  using proxy: false
2024-12-11 20:55:19,567 [Thread-13] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:713] WARN - Problem with lookup service while on the step: First checking lookup client and server are in sync
2024-12-11 20:55:19,567 [Thread-8] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:713] WARN - Problem with lookup service while on the step: First checking lookup client and server are in sync
2024-12-11 20:55:19,567 [Thread-13] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:715] WARN -

Could you please help me to explain the reason?

**Comment by emilyhyde** [comment]
We are having this same error, haven't been able to determine a fix yet either.

**Comment by qkqk-hub** [comment]
Ok, thank you for your reply, I will try the solution you provided! But please do not close this issue, because I tried to use `-dp` before, but after quite a long time passed, no progress bar like the following was generated, 

![image](https://github.com/user-attachments/assets/2343ee55-651d-4ca6-9b3e-4061ea2cc4bc)

I think I will encounter such a problem again, thank you!

**Comment by qkqk-hub** [comment]
After a week of operation, the progress bar finally appeared:
![image](https://github.com/user-attachments/assets/26059616-f427-4e86-9dd7-9d1145645d7c)

Then I just need to wait, thank you again for your help! I'm going to close this issue.

**Comment by matthiasblum** [comment]
@qkqk-hub this is because you submitted a high number of sequences. InterProScan isn't very efficient with large inputs. We recommend splitting large inputs in smaller ones (~30k protein sequences, or 5-10k nucleotide sequences).

**Comment by qkqk-hub** [comment]
Ok, thank you for reminding me again! Thank you!
