### ISSUE TITLE
error while loading shared libraries: libgnutls.so.28: ca nnot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dryak01** [ebi-pf-team/interproscan#44]
Hi, 

I have just installed interproscan  on a cluster running linux:
**version**
InterProScan version 5.26-65.0
InterProScan 64-Bit build  (requires  Java 1.8)

**System:**
linux 2.6.32-696.10.3.el6.x86_64 #1 SMP Tue Sep 26 18:14:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
perl, v5.10.1 (*) built for x86_64-linux-thread-multi
Python 2.7.10
'java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

I am getting the following error outputs when running the test command (with or without the -dp option)
`./interproscan.sh -i test_proteins.fasta -f tsv &>out_test1`

**out_test1:**
14/11/2017 09:27:40:445 Welcome to InterProScan-5.26-65.0
14/11/2017 09:27:48:973 Running InterProScan v5 in STANDALONE mode... on Linux
14/11/2017 09:27:58:978 Loading file /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/test_proteins.fasta
14/11/2017 09:27:58:981 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.1.0,Hamap-201701.18,MobiDBLite-1.0,PANTHER-12.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-20.132,ProSiteProfiles-20.132,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2017-11-14 09:28:08,156 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobCDD/000000000001_000000000006.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

2017-11-14 09:28:08,159 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobCDD/000000000001_000000000006.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-11-14 09:28:08,160 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepCDDRunBinaryRPSblast
2017-11-14 09:28:08,183 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 4 is being re-run following a failure.
14/11/2017 09:28:09:699 29% completed
2017-11-14 09:28:13,199 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobCDD/000000000001_000000000006.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

2017-11-14 09:28:13,200 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.6.0+/rpsblast -query /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobCDD/000000000001_000000000006.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-11-14 09:28:13,200 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepCDDRunBinaryRPSblast
2017-11-14 09:28:13,232 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 4 is being re-run following a failure.
2017-11-14 09:28:14,955 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/3/sfld_sites.annot -a /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.align.out -O /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.out -d /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

2017-11-14 09:28:14,955 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/3/sfld_sites.annot -a /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.align.out -O /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.out -d /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /data/dpearton/working/my_interproscan/interproscan-5.26-65.0/temp/hippo1_20171114_092748970_dtwd//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2017-11-14 09:28:14,956 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2017-11-14 09:28:15,068 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 15 : Run sfld postprocessing binary for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2017-11-14 09:28:15,069 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2017-11-14 09:28:15,069 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:241] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:128)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by mifraser** [comment]
The binaries supplied with InterProScan should work on most Linux systems, however it looks like you'll need to recompile at least one of them on your system.

Please see https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#install-and-compiling-binaries-used-in-interproscan

And for the rpsblast binary that is giving this particular error the instructions are in https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#cdds-rpsblastrpsbproc

Hope that helps?

Thanks,

Matt

**Comment by dryak01** [comment]
Hello,

Thank you.  I did find that message after I posted - unfortunately the
version of c++ installed is not high enough to compile it and I do not have
the neccessary permissions to update it.  It appears as if I will not be
able to install it unfortunately.

Thank you for your help.

Yours,
Dave

**Comment by emilhaegglund** [comment]
I had the same error running using Ubuntu 16.04. I was able to get it running by downloading a fresh copy of precompiled blast and copy rpsblast to the binary folder in interproscan.
```
wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-x64-linux.tar.gz
tar xvf ncbi-blast-2.6.0+-x64-linux.tar.gz

# backup original version
cp bin/blast/ncbi-blast-2.6.0+/rpsblast bin/blast/ncbi-blast-2.6.0+/rpsblast.bak

# copy the new version to the binary folder
cp ncbi-blast-2.6.0+/bin/rpsblast bin/blast/ncbi-blast-2.6.0+/rpsblast
```

**Comment by kbvstmd** [comment]
All of your questions can be found here. https://qiita.com/okuman/items/73bebfd711d3f955c167

**Comment by prvst** [comment]
I just got the same error on Ubuntu 18.04. Compiling from source also failed with the following error:

```
[ERROR] Failed to execute goal on project interproscan-persistence: Could not resolve dependencies for project uk.ac.ebi.interpro.scan:interproscan-persistence:jar:5.19-58.0: Could not find artifact com.oracle.jdbc:com.springsource.oracle.jdbc:jar:10.2.0.2 in apache-maven-snapshots (http://repository.apache.org/snapshots/) -> [Help 1]
```

**Comment by ola-t** [comment]
@emilhaegglund thanks for a hint ```
RUN wget -O /opt/ncbi-blast-2.6.0+-x64-linux.tar.gz ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-x64-linux.tar.gz
RUN tar xvf ncbi-blast-2.6.0+-x64-linux.tar.gz

# copy the new version to the binary folder
RUN cp /opt/ncbi-blast-2.6.0+/bin/rpsblast /opt/interproscan/bin/blast/ncbi-blast-2.6.0+/rpsblast
``` helped

**Comment by ola-t** [comment]
@gsn7 why binary compiled against the version of gnutls that is in the system/image is not shipped with release?

**Comment by ola-t** [comment]
@holmrenser you may wish to try docker image to avoid these kind of issues, reedme in https://github.com/BioContainers/containers/tree/master/interproscan/5.30-69.0

**Comment by holmrenser** [comment]
@ola-t given that docker is not always available on all machines (i.e. running the docker daemon requires root priviliges, which is not always feasible) this is not always an option. Maybe it is an idea to make explicit on which systems interproscan is expected to work?  Like I said before: if I download the x64 binary everything is fine, and I expect many systems to be running 64bit. Does this mean interproscan is shipped with the 32bit binary?

**Comment by gsn7** [comment]
@holmrenser we will update the rpsblast binary in the next release. interprorscan is shipped with a 64bit binary but it seems dependencies were not wired properly when building the blast binaries

**Comment by ola-t** [comment]
@holmrenser did you try uDocker ?

**Comment by holmrenser** [comment]
@gsn7 thanks for the info, I will keep an eye on the next release!
@ola-t I had not heard of uDocker until now, thanks for the tip!

**Comment by gsn7** [comment]
new releases have better dependency resolution and if need be you can run singularity or docker using the InterProScan container at https://hub.docker.com/r/interpro/interproscan
