### ISSUE TITLE
Encountering Exception

### ISSUE THREAD

**Issue by sagnikbanerjee15** [ebi-pf-team/interproscan#49]
Hello,

I am running the following command:

<pre>
nohup /opt/rit/app/interproscan/5.15-54.0/interproscan.sh -i plantfdb_674.fas -b plantfdb_674_interproscan > plantfdb_674_interproscan.output 2> plantfdb_674_interproscan.error
</pre>

I am getting the following error:

<pre>
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'htmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Cannot resolve reference to bean 'freeMarkerConfigHtmlWriter' while setting bean property 'freeMarkerConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Cannot resolve reference to bean 'templateLoaderHtmlWriter' while setting bean property 'templateLoader'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateLoaderHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [freemarker.cache.FileTemplateLoader]: Constructor threw exception; nested exception is java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:171)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Cannot resolve reference to bean 'templateLoaderHtmlWriter' while setting bean property 'templateLoader'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateLoaderHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [freemarker.cache.FileTemplateLoader]: Constructor threw exception; nested exception is java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
	... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateLoaderHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [freemarker.cache.FileTemplateLoader]: Constructor threw exception; nested exception is java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
	... 25 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [freemarker.cache.FileTemplateLoader]: Constructor threw exception; nested exception is java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
	... 34 more
Caused by: java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:125)
	at java.security.AccessController.doPrivileged(Native Method)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:122)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 36 more

</pre>

The command runs fine when executed with -appl ProDom,Pfam but fails when all other application runs are requested.

Please help.

Thank you.

**Comment by mifraser** [comment]
Hi, this looks like a Java version issue. What version of Java are you running with?

InterProScan 5.15-54.0 is an old version, you'll need Java 7 for that. (The latest release requires Java 8). For more information on installation requirements see https://github.com/ebi-pf-team/interproscan/wiki/InstallationRequirements

Thanks,

Matt

**Comment by sagnikbanerjee15** [comment]
Thank you for the reply. The old version of InterProScan was installed on our server. Now I have installed a local copy with the most recent version and it works perfectly with Java 8.

Thanks
