### ISSUE TITLE
ps_scan.pl failed

### ISSUE THREAD

**Issue by wangxf133** [ebi-pf-team/interproscan#58]
Hi~
when I run  interproscan by the test_proteins.fasta , it is ok
but when i run interproscan by my data , it's wrong 
```
(python2) xiaofei@DESKTOP-U55QOF8:/mnt/e/Interproscan/interproscan-5.28-67.0$ ./interproscan.sh -i text.fasta -o ./text.xml -goterms -iprlookup -pa -f xml
06/04/2018 12:48:53:315 Welcome to InterProScan-5.28-67.0
06/04/2018 12:49:06:149 Running InterProScan v5 in STANDALONE mode... on Linux
06/04/2018 12:49:30:352 Loading file /mnt/e/Interproscan/interproscan-5.28-67.0/text.fasta
06/04/2018 12:49:30:359 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2017_10,MobiDBLite-1.0,PANTHER-12.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2017_09,ProSiteProfiles-2017_09,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2018-04-06 12:49:52,509 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps654258-1.tmp at bin/prosite/ps_scan.pl line 1960.

2018-04-06 12:49:52,732 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps654258-1.tmp at bin/prosite/ps_scan.pl line 1960.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy108.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
2018-04-06 12:49:52,737 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-04-06 12:49:52,756 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 20 is being re-run following a failure.
06/04/2018 12:49:53:931 25% completed
06/04/2018 12:50:24:371 51% completed
2018-04-06 12:52:23,150 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps156948-1.tmp at bin/prosite/ps_scan.pl line 1960.

2018-04-06 12:52:23,153 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps156948-1.tmp at bin/prosite/ps_scan.pl line 1960.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy108.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
2018-04-06 12:52:23,156 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-04-06 12:52:23,183 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 20 is being re-run following a failure.
2018-04-06 12:52:29,580 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps558160-1.tmp at bin/prosite/ps_scan.pl line 1960.

2018-04-06 12:52:29,582 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2017_09/prosite_models/PS01031.prf /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles/000000000001_000000000001.fasta C=6.5 > /mnt/e/Interproscan/interproscan-5.28-67.0/temp/DESKTOP-U55QOF8_20180406_124906148_7rbk//jobPrositeProfiles//DESKTOP-U55QOF8/tmpdir_000000000001_000000000001//ps558160-1.tmp at bin/prosite/ps_scan.pl line 1960.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy108.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
2018-04-06 12:52:29,585 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-04-06 12:52:29,675 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 20 : Run ps_scan.pl and pfscan Binary for selected proteins for proteins 1 to 1 has failed irretrievably.  Available StackTraces follow.
2018-04-06 12:52:29,676 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2018-04-06 12:52:29,677 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
2018-04-06 12:52:30,178 [responseMonitorJmsContainer-1] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper:127] WARN - SQL Error: 42102, SQLState: 42S02
2018-04-06 12:52:30,180 [responseMonitorJmsContainer-1] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper:129] ERROR - Table "STEP_EXECUTION" not found; SQL statement:
select stepexecut0_.id as id1_90_0_, stepexecut0_.time_completed as time_com2_90_0_, stepexecut0_.time_created as time_cre3_90_0_, stepexecut0_.exception_first_chunk as exceptio4_90_0_, stepexecut0_.proportion_completed as proporti5_90_0_, stepexecut0_.time_started_running as time_sta6_90_0_, stepexecut0_.state as state7_90_0_, stepexecut0_.step_instance_id as step_ins9_90_0_, stepexecut0_.time_submitted as time_sub8_90_0_, exceptionc1_.step_execution_id as step_exe1_12_1_, exceptionc1_.exception_chunks as exceptio2_12_1_, exceptionc1_.chunk_index as chunk_in3_1_, stepinstan2_.id as id1_91_2_, stepinstan2_.bottom_model as bottom_m2_91_2_, stepinstan2_.bottom_protein as bottom_p3_91_2_, stepinstan2_.step_id as step_id4_91_2_, stepinstan2_.time_created as time_cre5_91_2_, stepinstan2_.top_model as top_mode6_91_2_, stepinstan2_.top_protein as top_prot7_91_2_, dependsupo3_.step_instance_id as step_ins1_93_3_, stepinstan4_.id as depends_2_93_3_, stepinstan4_.id as id1_91_4_, stepinstan4_.bottom_model as bottom_m2_91_4_, stepinstan4_.bottom_protein as bottom_p3_91_4_, stepinstan4_.step_id as step_id4_91_4_, stepinstan4_.time_created as time_cre5_91_4_, stepinstan4_.top_model as top_mode6_91_4_, stepinstan4_.top_protein as top_prot7_91_4_, parameters5_.step_instance_id as step_ins1_92_5_, parameters5_.parameters as paramete2_92_5_, parameters5_.parameters_key as paramete3_5_ from public.step_execution stepexecut0_ left outer join public.exception_chunk exceptionc1_ on stepexecut0_.id=exceptionc1_.step_execution_id inner join public.step_instance stepinstan2_ on stepexecut0_.step_instance_id=stepinstan2_.id left outer join public.step_instance_step_instance dependsupo3_ on stepinstan2_.id=dependsupo3_.step_instance_id left outer join public.step_instance stepinstan4_ on dependsupo3_.depends_upon_id=stepinstan4_.id left outer join public.step_instance_parameters parameters5_ on stepinstan4_.id=parameters5_.step_instance_id where stepexecut0_.id=? [42102-189]
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```
thanks~

**Comment by gsn7** [comment]
this might be due to your system environment. does the following command work?
./interproscan.sh -i test_all_appl.fasta -dp

**Comment by nologo68** [comment]
is it possible that you had * in your fasta file?

Best
