### ISSUE TITLE
There was an ERROR - Command line failed with exit code: 17 

### ISSUE THREAD

**Issue by wangzhennan14** [ebi-pf-team/interproscan#66]
Hi,
    When I run interproscan, there was an error, 
    01/06/2018 23:06:42:682 Welcome to InterProScan-5.27-66.0
01/06/2018 23:06:49:407 Running InterProScan v5 in STANDALONE mode... on Linux
01/06/2018 23:07:02:404 Loading file /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/protein.fasta
01/06/2018 23:07:02:470 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.1.0,Hamap-2017_10,MobiDBLite-1.0,PANTHER-12.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2017_09,ProSiteProfiles-2017_09,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,T                           IGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
01/06/2018 23:08:28:238 Uploaded/Stored 69602 unique sequences for analysis
2018-06-01 23:08:50,323 [amqEmbeddedWorkerJmsContainer-12] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000003001_000000004000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

2018-06-01 23:08:50,324 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000027001_000000028000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

2018-06-01 23:08:50,324 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000016001_000000017000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

2018-06-01 23:08:50,324 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000066001_000000067000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

2018-06-01 23:08:50,456 [amqEmbeddedWorkerJmsContainer-12] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.                             All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000003001_000000004000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2018-06-01 23:08:50,456 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  A                           ll database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000016001_000000017000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2018-06-01 23:08:50,456 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  A                           ll database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000027001_000000028000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2018-06-01 23:08:50,461 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-06-01 23:08:50,461 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-06-01 23:08:50,460 [amqEmbeddedWorkerJmsContainer-12] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-06-01 23:08:50,457 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  A                           ll database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2017_09/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2017_09/prosite_models /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ips                           can/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles/000000066001_000000067000.fasta
Error output from binary:
Unable to create /vol2/agis/ruanjue_group/wangzhennan/assembly/wuhan-reannot/ipscan/temp/comput71_20180601_230649404_4ji8//jobPrositeProfiles//comput71 at bin/prosite/ps_scan.pl line 923.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2018-06-01 23:08:50,463 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-06-01 23:08:50,736 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 3797 is being re-run following a failure.
2018-06-01 23:08:50,738 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 3751 is being re-run following a failure.
2018-06-01 23:08:50,739 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 3661 is being re-run following a failure.
2018-06-01 23:08:50,740 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:137] WARN - StepInstance 3608 is being re-run following a failure.

what is the matter? Can you give me some advice to solve this?  
                                                                                                                         Wang

**Comment by gsn7** [comment]
are you able to run the following command `./interproscan.sh -i test_all_appl.fasta -f tsv -dp`?

**Comment by zjj19910** [comment]
Do you solve your problems? I had similar problems to you. But it finished anyway. I don't know if it's right or not. 

`24/03/2019 16:47:56:845 Welcome to InterProScan-5.33-72.0
24/03/2019 16:48:06:490 Running InterProScan v5 in STANDALONE mode... on Linux
24/03/2019 16:48:19:829 Loading file /home/zhudan/zjj/zhudan_interproscan/Bter_XP.pep
24/03/2019 16:48:19:834 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2019-03-24 16:48:31,938 [amqEmbeddedWorkerJmsContainer-16] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2018_02/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2018_02/prosite_models /home/zhudan/zjj/zhudan_interproscan/temp/node7_20190324_164806488_hg6s//jobPrositeProfiles/000000006001_000000007000.fasta
Error output from binary:
Unable to create /home/zhudan/zjj/zhudan_interproscan/temp/node7_20190324_164806488_hg6s//jobPrositeProfiles//node7 at bin/prosite/ps_scan.pl line 923.

2019-03-24 16:48:31,944 [amqEmbeddedWorkerJmsContainer-16] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 17
Command: bin/prosite/ps_scan.pl -d data/prosite/2018_02/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2018_02/prosite_models /home/zhudan/zjj/zhudan_interproscan/temp/node7_20190324_164806488_hg6s//jobPrositeProfiles/000000006001_000000007000.fasta
Error output from binary:
Unable to create /home/zhudan/zjj/zhudan_interproscan/temp/node7_20190324_164806488_hg6s//jobPrositeProfiles//node7 at bin/prosite/ps_scan.pl line 923.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2019-03-24 16:48:31,945 [amqEmbeddedWorkerJmsContainer-16] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2019-03-24 16:48:32,221 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 461 is being re-run following a failure.
24/03/2019 19:04:44:465 25% completed
24/03/2019 20:04:44:747 30% completed
24/03/2019 21:04:45:053 34% completed
24/03/2019 22:04:45:358 37% completed
24/03/2019 23:05:26:234 46% completed
25/03/2019 00:05:26:412 50% completed
25/03/2019 01:05:26:566 61% completed
25/03/2019 02:05:26:661 62% completed
25/03/2019 03:05:45:307 66% completed
25/03/2019 04:06:13:078 80% completed
25/03/2019 05:06:30:343 93% completed
25/03/2019 06:10:09:176 99% completed
25/03/2019 07:15:54:632 99% completed
25/03/2019 08:16:23:348 99% completed
25/03/2019 08:17:30:208 100% done:  InterProScan analyses completed`

**Comment by XK4959** [comment]
Hello, I encountered the same problem @zjj19910 and got a 100% result, but I don’t know if this result can be used? How to solve the error 17? Is the file path too long?
