### ISSUE TITLE
when i run my data , why report an error like code , but when run test_protein.fasta is good

### ISSUE THREAD

**Issue by wangxf133** [ebi-pf-team/interproscan#68]
``08/06/2018 03:27:02:576 Welcome to InterProScan-5.29-68.0
08/06/2018 03:27:15:478 Running InterProScan v5 in STANDALONE mode... on Linux
08/06/2018 03:27:34:746 Loading file /mnt/e/Interproscan/interproscan-5.29-68.0/iwgsc_geneID_seq.fasta
08/06/2018 03:27:34:753 Running the following analyses:
[PANTHER-12.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2018-06-08 03:28:54,732 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:28:54,735 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:319] WARN - Problem with lookup service while on the step: Get
 matches of proteins analysed previously
2018-06-08 03:28:54,736 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:321] WARN -

The following problem was encountered by the pre-calculated match lookup service:
www.ebi.ac.uk:80 failed to respond
Pre-calculated match lookup service failed - analysis proceeding to run locally
============================================================

The pre-calculated match lookup service has been configured in the interproscan.properties file.
  precalculated match lookup service url : http://www.ebi.ac.uk/interpro/match-lookup
  precalculated match lookup service proxy host :   proxy port : 3128

Unfortunately the web service has failed. Check the configuration of this service
in the interproscan.properties file and, if necessary, set the following property to look like this:

precalculated.match.lookup.service.url=

If the problem persists, check if this is a firewall or proxy issue. If it is a proxy issue, then setting
the following property in the interproscan.properties file should work:

precalculated.match.lookup.service.proxy.host=
precalculated.match.lookup.service.proxy.port=

If this still does not work please inform the InterPro team of this error
by sending an email to:

interhelp@ebi.ac.uk

In the meantime, the analysis will continue to run locally.

2018-06-08 03:30:37,266 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:31:11,007 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:31:23,267 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:33:50,226 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:34:38,693 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:34:40,102 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false
2018-06-08 03:41:29,739 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/
match-lookup is accessible - code: 302,  using proxy: false

**Comment by gsn7** [comment]
are you able to run the following command ./interproscan.sh -i test_all_appl.fasta -f tsv -dp?
we will look into improving the error messages to make them more clear.

**Comment by elainfl** [comment]
Hello, I have the same problem and I run the code you provide above. I get this; 
`/home/elena/programasseq/interproscan-5.35-74.0/interproscan.sh -i /home/elena/programasseq/interproscan-5.35-74.0/test_all_appl.fasta -f tsv -dp
05/07/2019 10:42:22:217 Welcome to InterProScan-5.35-74.0
05/07/2019 10:42:27:586 Running InterProScan v5 in STANDALONE mode... on Linux
05/07/2019 10:42:38:386 Loading file /home/elena/programasseq/interproscan-5.35-74.0/test_all_appl.fasta
05/07/2019 10:42:38:398 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2019_01,MobiDBLite-2.0,PANTHER-14.1,Pfam-32.0,Phobius-1.01,PIRSF-3.02,PRINTS-42.0,ProSitePatterns-2019_01,ProSiteProfiles-2019_01,SFLD-4,SignalP_EUK-4.1,SignalP_GRAM_NEGATIVE-4.1,SignalP_GRAM_POSITIVE-4.1,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0,TMHMM-2.0c]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2019-07-05 10:42:44,937 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "bin/phobius/1.01/phobius.pl": error=2, No existe el fichero o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2019-07-05 10:42:44,940 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPhobiusRunBinary
2019-07-05 10:42:45,056 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 86 is being re-run following a failure.
2019-07-05 10:42:45,074 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 2
Command: perl bin/signalp/4.1/signalp -T 
Error output from binary:
Can't locate FASTA.pm in @INC (you may need to install the FASTA module) (@INC contains: /home/elena/programasseq/signalp-4.1/signalp/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at bin/signalp/4.1/signalp line 80.
BEGIN failed--compilation aborted at bin/signalp/4.1/signalp line 80.

2019-07-05 10:42:45,076 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 2
Command: perl bin/signalp/4.1/signalp -T 
Error output from binary:
Can't locate FASTA.pm in @INC (you may need to install the FASTA module) (@INC contains: /home/elena/programasseq/signalp-4.1/signalp/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at bin/signalp/4.1/signalp line 80.
BEGIN failed--compilation aborted at bin/signalp/4.1/signalp line 80.

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2019-07-05 10:42:45,077 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepSignalPGramNegativeTempOptionCheck
2019-07-05 10:42:45,176 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 84 is being re-run following a failure.`
What can I do? thanks

**Comment by gsn7** [comment]
it looks like you have installed SignalP, Phobius and TMHMM but InterProScan is not picking SignalP up. This might be due to permissions. 
- Check what permissions are for the signalp:  what is the output of the command 
ls -l /home/elena/programasseq/interproscan-5.35-74.0/bin/signalp/4.1/signalp

**Comment by elainfl** [comment]
`-rwxr-xr-x 1 elena elena 33048 jul  3 13:43 /home/elena/programasseq/interproscan-5.35-74.0/bin/signalp/4.1/signalp`

**Comment by gsn7** [comment]
the permission look ok. but you might not have installed SignlaP correctly. the directly 'bin/signalp/4.1/lib' should include a FASTA.pm file and it seems missing
whats the output of running the command :
perl /home/elena/programasseq/interproscan-5.35-74.0/bin/signalp/4.1/signalp -T

**Comment by elainfl** [comment]
Hello, it is true since I had already installed SignalP in my server but I only copied the program and not the extra folds that the program use. I rerun Interproscan again, and I got the same problem than earlier. 

`**The following problem was encountered by the pre-calculated match lookup service**:
**Could not determine server version**
Pre-calculated match lookup service failed - analysis proceeding to run locally
============================================================

The pre-calculated match lookup service has been configured in the interproscan.properties file.  
  precalculated match lookup service url : http://www.ebi.ac.uk/interpro/match-lookup
  precalculated match lookup service proxy host :   proxy port : 3128

**Unfortunately the web service has failed. Check the configuration of this service
in the interproscan.properties file and, if necessary, set the following property to look like this**:

precalculated.match.lookup.service.url=

If the problem persists, check if this is a firewall or proxy issue. If it is a proxy issue, then setting 
the following property in the interproscan.properties file should work:

precalculated.match.lookup.service.proxy.host=
precalculated.match.lookup.service.proxy.port=

If this still does not work please inform the InterPro team of this error
by sending an email to:

interhelp@ebi.ac.uk

In the meantime, the analysis will continue to run locally.


2019-07-05 13:46:30,363 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:481] WARN - lookupUp service at http://www.ebi.ac.uk/interpro/match-lookup is accessible - code: 500,  using proxy: false
`

**Comment by mifraser** [comment]
"The following problem was encountered by the pre-calculated match lookup service:
Could not determine server version
Pre-calculated match lookup service failed - analysis proceeding to run locally" message is because the default lookup service hosted at the EBI could not be reached.

This doesn't apply to the original issue (8th June), but certainly as of late last week the default EBI hosted service has been temporarily unavailable. Sorry for the inconvenience. 

It is a warning message but is not a failure so your InterProScan should still continue to run. It's optional and you can disable the use of the service using the "-dp" option to stop getting this message. 

The default lookup service will soon be updated for the next version of InterProScan.

More information:

https://github.com/ebi-pf-team/interproscan/wiki/LocalLookupService#what-is-the-interproscan-5-lookup-service

**Comment by gsn7** [comment]
the issues appear to have been resolved. if not open a new ticket

**Comment by JanVHenkel** [comment]
I got the same error message and followed your suggestions. 

with:
perl /home/elena/programasseq/interproscan-5.35-74.0/bin/signalp/4.1/signalp -T
(adapted to my file destination)

i got the output:
Can't locate FASTA.pm in @INC (you may need to install the FASTA module) (@INC contains: /usr/opt/www/pub/CBS/services/SignalP-4.1/signalp-4.1/lib /home/janvhenkel/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/janvhenkel/miniconda3/lib/site_perl/5.26.2 /home/janvhenkel/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/janvhenkel/miniconda3/lib/5.26.2 .) at /home/janvhenkel/my_interproscan/interproscan-5.48-83.0/bin//signalp/4.1/signalp line 80.
BEGIN failed--compilation aborted at /home/janvhenkel/my_interproscan/interproscan-5.48-83.0/bin//signalp/4.1/signalp line 80.

I looked into lib wherei find FASTA.pm (only file in this directory)

Can you help my with this?
