### ISSUE TITLE
Command line failed with exit code: 25 on test_all_appl.fasta

### ISSUE THREAD

**Issue by rafiko1** [ebi-pf-team/interproscan#69]
Hi, I had same problem as a closed issue before (see Issue #58)
When I run the following command: `./interproscan.sh -i test_all_appl.fasta -dp`
I get an error with as last lines seen bellow. Somebody said it can be related to my system environment.
Is there anything I can do about it?
```
2018-06-16 16:57:10,294 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2018_02/prosite.dat -w bin/prosite/pfsearch -s -m -o gff -y data/prosite/2018_02/prosite_models /home/rafiko1/my_interproscan/interproscan-5.29-68.0/temp/LAPTOP-GRM7SB3G_20180616_165546557_i7v4//jobPrositeProfiles/000000000001_000000000004.fasta
Error output from binary:
bin/prosite/pfsearch: 1: bin/prosite/pfsearch: Syntax error: "(" unexpected
Could not execute bin/prosite/pfsearch -f -lxz data/prosite/2018_02/prosite_models/PS01031.prf /home/rafiko1/my_interproscan/interproscan-5.29-68.0/temp/LAPTOP-GRM7SB3G_20180616_165546557_i7v4//jobPrositeProfiles/000000000001_000000000004.fasta C=6.5 > /home/rafiko1/my_interproscan/interproscan-5.29-68.0/temp/LAPTOP-GRM7SB3G_20180616_165546557_i7v4//jobPrositeProfiles//LAPTOP-GRM7SB3G/tmpdir_000000000001_000000000004//ps607910-1.tmp at bin/prosite/ps_scan.pl line 1960.

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy108.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
2018-06-16 16:57:10,315 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
2018-06-16 16:57:10,348 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 25 : Run ps_scan.pl and pfscan Binary for selected proteins for proteins 1 to 4 has failed irretrievably.  Available StackTraces follow.
2018-06-16 16:57:10,351 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2018-06-16 16:57:10,352 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```

**Comment by gsn7** [comment]
on what linux distribution  are you running?
what is the shell you are using? 
what is the output of the command?
`echo $0`

**Comment by rafiko1** [comment]
I'm running it on Ubuntu (16.04.4 LTS (Xenial Xerus), however within the Windows Linux Subsystem - I'm not certain whether that make a difference.
Output of the command echo $0 is:

> -- bash 

So it is using the Bourne Again Shell.

**Comment by gsn7** [comment]
the problem has to do with Windows Linux Subsystem. We have never tested InterProScan on WLS and those who have tried to run on it have faced problems. 
If you have access to a native linux distribution, I would advise you use that.

**Comment by fgcilingir** [comment]
Hello,

I get errors with the same exit code (25) when I try running
`./interproscan.sh -i test_all_appl.fasta -f tsv -dp`

You can find the log file, attached.

I use Ubuntu 16.04 (within a cluster, no Windows Linux Subsystem whatsoever), have python3.12, open jdk 11.0.9.1 and perl 5.22 in my environment. I tried compiling prosite binaries by myself but it did not work. 

Could you please help me to find what the problem is?
[interpro_test1.log](https://github.com/ebi-pf-team/interproscan/files/7476311/interpro_test1.log)
