### ISSUE TITLE
pantherScore.pl error

### ISSUE THREAD

**Issue by dlepp** [ebi-pf-team/interproscan#7]
Hi there, I'm getting the error messages below when trying to run a multifasta protein file of ~3000 sequences. The test file runs without error.  I notice that the perl command has the parameter -I before the script name pantherScore.pl, not sure if this has something to do with it.  I am using interproscan-5.18-57.0.

Thanks, 

Dion

07/06/2016 11:02:00:499 Running the following analyses:
[SignalP_EUK-4.1,PIRSF-3.01,Pfam-29.0,SignalP_GRAM_POSITIVE-4.1,TMHMM-2.0c,PRINTS-42.0,ProSiteProfiles-20.119,PANTHER-10.0,Coils-2.2.1,Hamap-201511.02,ProSitePatterns-20.119,SUPERFAMILY-1.75,ProDom-2006.1,SMART-7.1,SignalP_GRAM_NEGATIVE-4.1,Gene3D-3.5.0,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2016-06-07 11:19:08,457 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:156] ERROR - Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

2016-06-07 11:19:08,462 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:158)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy96.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2016-06-07 11:19:08,465 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:203] ERROR - StepExecution with errors - stepName: stepPantherRunBinary
2016-06-07 11:19:08,644 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:72] WARN - StepInstance 54 is being re-run following a failure.
07/06/2016 11:22:36:871 25% completed
2016-06-07 11:23:32,036 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:156] ERROR - Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

2016-06-07 11:23:32,037 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:158)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy96.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2016-06-07 11:23:32,038 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:203] ERROR - StepExecution with errors - stepName: stepPantherRunBinary
2016-06-07 11:23:32,117 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:72] WARN - StepInstance 54 is being re-run following a failure.
2016-06-07 11:24:59,216 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:156] ERROR - Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

2016-06-07 11:24:59,216 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:201] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 255
Command: perl -I bin/panther/pantherScore/1.04/lib bin/panther/pantherScore/1.04/pantherScore.pl -l /media/4tb1/Users/leppd/Shared/Panther -D I -E 1e-3 -n -c 1 -B bin/blast/2.2.24/bin/blastall -H bin/hmmer/hmmer2/2.3.2/hmmsearch -i /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw//jobPanther/000000000501_000000000921.fasta -T /media/4tb1/tmp/panther_tmp_files 
Error output from binary:

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:158)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy96.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:189)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2016-06-07 11:24:59,217 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:203] ERROR - StepExecution with errors - stepName: stepPantherRunBinary
2016-06-07 11:24:59,264 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 54 : Run PANTHER binary for selected proteins for proteins 501 to 921 has failed irretrievably.  Available StackTraces follow.
2016-06-07 11:24:59,267 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2016-06-07 11:24:59,267 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:145] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:63)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:326)
2016-06-07 11:24:59,312 [main] [uk.ac.ebi.interpro.scan.jms.master.AbstractMaster:249] WARN - Unable to delete temporary directory /media/Scratch/Users/dlepp/TZ2_MycotoxGenome/MiSeq_run2/temp/Onguel669835_20160607_110149684_kanw
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by dlepp** [comment]
Just an update, I've narrowed it down to an issue with the protein sequence itself.  If I paste one of my protein sequences into the test_proteins.fasta file, then the analysis with the test file will fail as well.

**Comment by dlepp** [comment]
It appears to have spontaneously corrected itself, not sure what the issue was as I didn't change anything.

In the error message it suggests to check the log file - where would I find this file?

**Comment by gsn7** [comment]
the error message doesn't have the information to pinpoint what might be happening. previously the Panther script has given such errors on encountering transient file system problems.
