### ISSUE TITLE
Problems in the test running

### ISSUE THREAD

**Issue by souzaems** [ebi-pf-team/interproscan#79]
Hi, everyone
I already install the program and I tried to run the simple commando 
`./interproscan.sh -i test_proteins.fasta -f tsv`

I ran in my lab server and the error was:

`09/10/2018 11:52:44:672 Welcome to InterProScan-5.31-70.0
09/10/2018 11:52:51:422 Running InterProScan v5 in STANDALONE mode... on Linux
09/10/2018 11:53:10:854 Loading file /dados/erica/my_interproscan/interproscan-5.31-70.0/test_proteins.fasta
09/10/2018 11:53:10:857 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
09/10/2018 11:53:22:436 26% completed
2018-10-09 11:53:27,537 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/4/sfld_sites.annot -a /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.align.out -O /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.out -d /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

2018-10-09 11:53:27,540 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/4/sfld_sites.annot -a /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.align.out -O /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.out -d /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /dados/erica/my_interproscan/interproscan-5.31-70.0/temp/srv-centos-prof-mariana.ib.unicamp.br_20181009_115251421_j6a1//jobSFLD/000000000001_000000000006_one.raw.out 
Error output from binary:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
2018-10-09 11:53:27,541 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2018-10-09 11:53:27,666 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 6 : Run sfld postprocessing binary for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2018-10-09 11:53:27,668 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2018-10-09 11:53:27,668 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details`

Could you help me?

**Comment by gsn7** [comment]
what is the output of the command?
`ldd --version|grep libc`

you may have to compile the SFLD binary that is causing the problem, see https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#sfld_preprocesssfld_postprocess-used-by-sfld

**Comment by souzaems** [comment]
Hi

I used the command and that was the results:

`eduroam-177-220-46-91:Documents newuser$ ldd --version|grep libc
-bash: ldd: command not found
eduroam-177-220-46-91:Documents newuser$ ldd --version
-bash: ldd: command not found`

**Comment by souzaems** [comment]
Hi

I used the command and the result was:

`ldd (GNU libc) 2.12`

**Comment by gsn7** [comment]
i am closing this issue, unless it has not been resolved. then do re-open it
