### ISSUE TITLE
Problem running InterProScan-5.32-71.0

### ISSUE THREAD

**Issue by pbravakos** [ebi-pf-team/interproscan#81]
I have installed both interproscan-5.31-70.0 and InterProScan-5.32-71.0 on a cluster.
interproscan-5.31-70.0 runs without any problems. InterProScan-5.32-71.0 runs the test ./interproscan.sh -i test_proteins.fasta -f tsv succesfully, but when i try to run it on real data I get an error, although interproscan-5.31-70.0 on the same data runs succesfully. Bellow is the error message i get from InterProScan-5.32-71.0 output:
```
Start Interproscan analysis

14/11/2018 09:31:47:183 Welcome to InterProScan-5.32-71.0
14/11/2018 09:31:53:293 Running InterProScan v5 in STANDALONE mode... on Linux
14/11/2018 09:32:06:800 Loading file Str02_InterProScan_amino-acid-sequences.fasta
14/11/2018 09:32:06:804 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,Phobius-1.01,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMI
LY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
14/11/2018 09:42:18:129 25% completed
14/11/2018 09:49:38:042 50% completed
14/11/2018 10:04:54:897 75% completed
14/11/2018 10:17:59:219 90% completed
14/11/2018 11:18:18:081 99% completed
2018-11-14 11:20:17,149 [amqEmbeddedWorkerJmsContainer-14] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All
database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to writeComment output from InterProScan to path: .../Str02_interpro-output_1.json
        at uk.ac.ebi.interpro.scan.management.model.implementations.WriteOutputStep.execute(WriteOutputStep.java:246)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at java.io.Writer.write(Writer.java:157)
        at uk.ac.ebi.interpro.scan.io.match.writer.ProteinMatchesJSONResultWriter.write(ProteinMatchesJSONResultWriter.java:70)
        at uk.ac.ebi.interpro.scan.management.model.implementations.WriteOutputStep.outputToJSON(WriteOutputStep.java:358)
        at uk.ac.ebi.interpro.scan.management.model.implementations.WriteOutputStep.execute(WriteOutputStep.java:216)
        ... 23 more
        Suppressed: java.nio.charset.UnmappableCharacterException: Input length = 1
                at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
                at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
                at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
                at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
                at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
                at java.io.BufferedWriter.close(BufferedWriter.java:265)
                at uk.ac.ebi.interpro.scan.io.match.writer.ProteinMatchesJSONResultWriter.close(ProteinMatchesJSONResultWriter.java:83)
                at uk.ac.ebi.interpro.scan.management.model.implementations.WriteOutputStep.outputToJSON(WriteOutputStep.java:359)
                ... 24 more
2018-11-14 11:20:17,164 [amqEmbeddedWorkerJmsContainer-14] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepWriteOutput
2018-11-14 11:20:17,369 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 382 : Write output for completed analysis for proteins 1 to 4780 has failed irretrievably.  Available StackTraces follow.
2018-11-14 11:20:17,370 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2018-11-14 11:20:17,370 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
```
If you have any idea why this could be happening, please tell me.
Thanks

**Comment by keshavd** [comment]
I'm having this same issue. Does this only happen when you're writing in JSON format?

**Comment by matthiasblum** [comment]
Hi @pbravakos and @keshavd ,
When updating Pfam 32.0 in InterPro, we found these invalid symbols and reported the issue to the Pfam team. Internally (at least at the [database](https://www.ebi.ac.uk/interpro/beta/entry/pfam/PF17764/) level), we replaced these symbols by interrogation marks, and I would have expected the same for InterProScan. I'll ask the InterProScan devs tomorrow.

**Comment by keshavd** [comment]
Awesome. In each of the truncated output files from InterProScan, this was Pfam entry that threw the error. I hope this helps.

**Comment by mifraser** [comment]
Thank you all for the extra information to help us reproduce this problem!

This seems locale dependant. InterProScan works for me on British/UTF-8, if I type "locale" at the Linux termial I get:

$ locale
LANG=en_GB.UTF-8
...
LANG_ALL=

So I guess you are on a different locale to me. When I changed it to:

export LANG=en_GB.iso8859-1

...I could then see the error.

Sorry for the inconvenience, we'll look into this.

**Comment by keshavd** [comment]
I called ```export LANG=en_GB.UTF-8``` before launching interproscan and it ran to completion! Cheers!

**Comment by pbravakos** [comment]
Hi @mifraser, @keshavd,
Thanks for resolving this issue. I haven't tried it yet, but i intend to test it soon.

**Comment by mifraser** [comment]
In InterProScan 5.33-72.0 you should no longer get this error. The unknown characters are removed.

**Comment by kishor2019** [comment]
Hi @matthiasblum @mifraser 
I am having the same issue while running interproscan 5.48-83.0. Could you please help me find a way to resolve the issue?

**Comment by shamshad1987** [comment]
Hi all, I am having same issue any resolution? Thanks in advance

InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster.

**Comment by BohanWW** [comment]
> Hi all, I am having same issue any resolution? Thanks in advance
> 
> InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster.

I am having the same issue and i would like to know how you solved it
