### ISSUE TITLE
Problems running python RESTful client

### ISSUE THREAD

**Issue by boboppie** [ebi-pf-team/interproscan#82]
Dear team,

I downloaded the python client *iprscan5.py* from [here](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=54652041).  

My input is TEST.fa:
```
>sp|P35858|ALS_HUMAN Insulin-like growth factor-binding protein complex acid labile subunit OS=Homo sapiens GN=IGFALS PE=1 SV=1
MALRKGGLALALLLLSWVALGPRSLEGADPGTPGEAEGPACPAACVCSYDDDADELSVFC
SSRNLTRLPDGVPGGTQALWLDGNNLSSVPPAAFQNLSSLGFLNLQGGQLGSLEPQALLG
LENLCHLHLERNQLRSLALGTFAHTPALASLGLSNNRLSRLEDGLFEGLGSLWDLNLGWN
SLAVLPDAAFRGLGSLRELVLAGNRLAYLQPALFSGLAELRELDLSRNALRAIKANVFVQ
LPRLQKLYLDRNLIAAVAPGAFLGLKALRWLDLSHNRVAGLLEDTFPGLLGLRVLRLSHN
AIASLRPRTFKDLHFLEELQLGHNRIRQLAERSFEGLGQLEVLTLDHNQLQEVKAGAFLG
LTNVAVMNLSGNCLRNLPEQVFRGLGKLHSLHLEGSCLGRIRPHTFTGLSGLRRLFLKDN
GLVGIEEQSLWGLAELLELDLTSNQLTHLPHRLFQGLGKLEYLLLSRNRLAELPADALGP
LQRAFWLDVSHNRLEALPNSLLAPLGRLRYLSLRNNSLRTFTPQPPGLERLWLEGNPWDC
GCPLKALRDFALQNPSAVPRFVQAICEGDDCQPPAYTYNNITCASPPEVVGLDLRDLSEA
HFAPC
```

I ran a command:
```
python3 iprscan5.py --sequence TEST.fa --email MYEMAIL
```

Output on terminal:
```
JobId: iprscan5-R20190111-120600-0775-43814494-p2m
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
FINISHED
Creating result file: iprscan5-R20190111-120600-0775-43814494-p2m.out.txt
Creating result file: iprscan5-R20190111-120600-0775-43814494-p2m.log.txt
Traceback (most recent call last):
  File "iprscan5.py", line 556, in <module>
    getResult(jobId)
  File "iprscan5.py", line 394, in getResult
    fh.write(result)
TypeError: write() argument must be str, not bytes
```
iprscan5-R20190111-120600-0775-43814494-p2m.out.txt:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" interproscan-version="5.32-71.0">
    <protein>
        <sequence md5="bdcd8a4f03c0423c08bf84df20c58702">MALRKGGLALALLLLSWVALGPRSLEGADPGTPGEAEGPACPAACVCSYDDDADELSVFCSSRNLTRLPDGVPGGTQALWLDGNNLSSVPPAAFQNLSSLGFLNLQGGQLGSLEPQALLGLENLCHLHLERNQLRSLALGTFAHTPALASLGLSNNRLSRLEDGLFEGLGSLWDLNLGWNSLAVLPDAAFRGLGSLRELVLAGNRLAYLQPALFSGLAELRELDLSRNALRAIKANVFVQLPRLQKLYLDRNLIAAVAPGAFLGLKALRWLDLSHNRVAGLLEDTFPGLLGLRVLRLSHNAIASLRPRTFKDLHFLEELQLGHNRIRQLAERSFEGLGQLEVLTLDHNQLQEVKAGAFLGLTNVAVMNLSGNCLRNLPEQVFRGLGKLHSLHLEGSCLGRIRPHTFTGLSGLRRLFLKDNGLVGIEEQSLWGLAELLELDLTSNQLTHLPHRLFQGLGKLEYLLLSRNRLAELPADALGPLQRAFWLDVSHNRLEALPNSLLAPLGRLRYLSLRNNSLRTFTPQPPGLERLWLEGNPWDCGCPLKALRDFALQNPSAVPRFVQAICEGDDCQPPAYTYNNITCASPPEVVGLDLRDLSEAHFAPC</sequence>
        <xref id="sp|P35858|ALS_HUMAN" name="sp|P35858|ALS_HUMAN Insulin-like growth factor-binding protein complex acid labile subunit OS=Homo sapiens GN=IGFALS PE=1 SV=1"/>
        <matches/>
    </protein>
</protein-matches>
```

iprscan5-R20190111-120600-0775-43814494-p2m.log.txt:
```
11/01/2019 12:06:02:673 Welcome to InterProScan-5.32-71.0
11/01/2019 12:06:13:278 Running InterProScan v5 in SINGLESEQ mode... on Linux
11/01/2019 12:06:27:921 Running the following analyses:
[MobiDBLite-2.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
11/01/2019 12:06:32:020 100% done:  InterProScan analyses completed
```
The default output is a tsv (iprscan5-R20190111-120600-0775-43814494-p2m.tsv.txt), but due to the error, there is no content in the file.

Then I tried:
```
python3 iprscan5.py --polljob --jobid iprscan5-R20190111-120600-0775-43814494-p2m --outformat gff
```
However, iprscan5-R20190111-120600-0775-43814494-p2m.gff.txt has no result:
```
##gff-version 3
##feature-ontology http://song.cvs.sourceforge.net/viewvc/song/ontology/sofa.obo?revision=1.269
##interproscan-version 5.32-71.0
##FASTA
```

The first problem is there is an error when I save the results as tsv. The second problem (when save as a different format) is there is no match for my query, but when I submitted a job on the webform, it returned the results just fine. Is there something I missed in my run? Could you please advise?

Best wishes,
Fengyuan

**Comment by mifraser** [comment]
Hi Fengyuan,

Thank you for reporting this. I'm unsure of the latest status with the example iprscan5.py as the web services are maintained by a different team. But I've passed these observations on. For future reference their contact details are at the bottom of the page you downloaded iprscan5.py from.

From what I can see, in the example iprscan5.py the --appl parameter is defaulting to MobiDB only and there are no MobiDB matches for that sequence. That's because of these lines that stop it running all applications by default:

```
   if not options.appl:
        params['appl'] = 'MobiDBLite'
```
Kind regards,

Matt

**Comment by biomadeira** [comment]
@boboppie Matt is completely right. I have updated all the clients as there was a bug with our lookup for default values, which affected the `--appl` parameter. See the new version in https://github.com/ebi-wp/webservice-clients/blob/master/python/iprscan5.py
