### ISSUE TITLE
Continuing Issue with Linux64 and StandaloneBlackBoxMaster

### ISSUE THREAD

**Issue by stsmall** [ebi-pf-team/interproscan#86]
Hi,
I am attempting to use Interproscan-5.33-72.0 on a Linux 64 bit machine. The test files run without error but a larger file, 15 entry fasta file, causes an error. 
thank you for your help and supporting a great program!

I have pasted the error below:

Matches for any sequences that are not represented in the lookup service will be calculated locally.
07/02/2019 12:36:22:603 26% completed
2019-02-07 12:36:27,655 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/4/sfld_sites.annot -a /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.align.out -O /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.out -d /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006_one.raw.out
Error output from binary:
feat

2019-02-07 12:36:27,663 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/sfld/sfld_postprocess -s data/sfld/4/sfld_sites.annot -a /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.align.out -O /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.out -d /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006.raw.domtblout.out -o /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg//jobSFLD/000000000001_000000000006_one.raw.out
Error output from binary:
feat

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2019-02-07 12:36:27,666 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepSFLDPostProcessorBinaryRun
2019-02-07 12:36:27,751 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 7 : Run sfld postprocessing binary for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2019-02-07 12:36:27,752 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2019-02-07 12:36:27,753 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
2019-02-07 12:36:28,281 [main] [uk.ac.ebi.interpro.scan.jms.master.AbstractMaster:249] WARN - Unable to delete temporary directory /afs/crc.nd.edu/user/s/ssmall2/ssmall2/Wb_analysis/interproscan-5.33-72.0/temp/rosalind.crc.nd.edu_20190207_123547112_21fg
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by gsn7** [comment]
what is the linux distribution n version you are running on? 
you might have to recompile the SFLD binary, check https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#sfld_preprocesssfld_postprocess-used-by-sfld
