### ISSUE TITLE
Problems running interpro.sh on my files

### ISSUE THREAD

**Issue by shimingt** [ebi-pf-team/interproscan#91]
Hello there,

I am trying to run interpro.sh on my multi-fasta file of amino acid sequences. 

This is my command: 
`#~/bin/bash
SAMPLE=MFC280618

```
interproscan.sh -i $SAMPLE.protein-sequences.fa \
			-f tsv \
			--goterms \
			--iprlookup \
			--pathways \
			-o $SAMPLE-interpro-output.tsv`
```
Attached is the following output:
`tanshiming@S620100019205:~/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio$ anvio_interpro.sh 
20/03/2019 10:09:07:020 Welcome to InterProScan-5.33-72.0
20/03/2019 10:09:14:271 Running InterProScan v5 in STANDALONE mode... on Linux
20/03/2019 10:09:27:251 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 10:09:27:255 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
20/03/2019 10:28:04:005 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 10:28:04:006 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.h2.util.StringUtils.getCache(StringUtils.java:70)
	at org.h2.util.StringUtils.fromCacheOrNew(StringUtils.java:932)
	at org.h2.command.Parser.read(Parser.java:3186)
	at org.h2.command.Parser.readIf(Parser.java:3127)
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:1950)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1973)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688)
	at org.h2.command.Parser.parseSelect(Parser.java:1676)
	at org.h2.command.Parser.parsePrepared(Parser.java:432)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
	at com.sun.proxy.$Proxy7.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1928)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1897)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1875)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2611)
20/03/2019 11:02:23:528 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 11:02:23:529 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
Exception in thread "ActiveMQ Broker[localhost] Scheduler" java.lang.OutOfMemoryError: Java heap space
20/03/2019 11:50:26:173 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 11:50:26:174 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
20/03/2019 12:25:18:571 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 12:25:18:572 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
20/03/2019 13:00:50:977 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 13:00:50:978 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
20/03/2019 13:34:55:687 Loading file /home/tanshiming/Documents/CaoBin/October-2018/trimmed_duk_kmer31/Assembly-Megahit/MFC280618_megahit/Anvio/MFC280618.protein-sequences.fa
20/03/2019 13:34:55:688 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-2.0,PANTHER-12.0,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2019-03-20 13:53:37,491 [ActiveMQ VMTransport: vm://localhost#1-12] [org.apache.activemq.broker.region.RegionBroker:814] WARN - Caught an exception sending to DLQ: Message ID:S620100019205-34277-1553047754031-3:1:11:1:1 dropped=false acked=false locked=true
java.lang.IllegalStateException: Timer already cancelled.
	at java.util.Timer.sched(Timer.java:397)
	at java.util.Timer.schedule(Timer.java:248)
	at org.apache.activemq.thread.Scheduler.executePeriodically(Scheduler.java:41)
	at org.apache.activemq.broker.region.Queue.start(Queue.java:949)
	at org.apache.activemq.broker.region.AbstractRegion.addDestination(AbstractRegion.java:161)
	at org.apache.activemq.broker.region.RegionBroker.addDestination(RegionBroker.java:348)
	at org.apache.activemq.broker.region.RegionBroker.sendToDeadLetterQueue(RegionBroker.java:804)
	at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
	at org.apache.activemq.advisory.AdvisoryBroker.sendToDeadLetterQueue(AdvisoryBroker.java:505)
	at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
	at org.apache.activemq.broker.BrokerFilter.sendToDeadLetterQueue(BrokerFilter.java:318)
	at org.apache.activemq.broker.MutableBrokerFilter.sendToDeadLetterQueue(MutableBrokerFilter.java:330)
	at org.apache.activemq.broker.region.PrefetchSubscription.sendToDLQ(PrefetchSubscription.java:540)
	at org.apache.activemq.broker.region.PrefetchSubscription.acknowledge(PrefetchSubscription.java:397)
	at org.apache.activemq.broker.region.AbstractRegion.acknowledge(AbstractRegion.java:526)
	at org.apache.activemq.broker.region.RegionBroker.acknowledge(RegionBroker.java:484)
	at org.apache.activemq.broker.BrokerFilter.acknowledge(BrokerFilter.java:87)
	at org.apache.activemq.broker.BrokerFilter.acknowledge(BrokerFilter.java:87)
	at org.apache.activemq.broker.TransactionBroker.acknowledge(TransactionBroker.java:276)
	at org.apache.activemq.broker.MutableBrokerFilter.acknowledge(MutableBrokerFilter.java:97)
	at org.apache.activemq.broker.TransportConnection.processMessageAck(TransportConnection.java:555)
	at org.apache.activemq.command.MessageAck.visit(MessageAck.java:245)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:338)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:188)
	at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
	at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:270)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

It has been stuck for quite sometime. Should I continue waiting?

Thanks!

**Comment by mifraser** [comment]
How many sequences are in your input file? It looks like it ran out of memory and may have failed.

There are some tips about improving performance if you have a large number of sequences (e.g. splitting large inputs into chunks which also reduces memory usage):

https://github.com/ebi-pf-team/interproscan/wiki/ImprovingPerformance

Does that help fix your issue?

Thanks,

Matt

**Comment by Devadas07** [comment]
./interproscan.sh: line 36: [[: OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:: syntax error in expression (error token is "64-Bit Server VM warning: Insufficient space for shared memory file:")
./interproscan.sh: line 36: [[: OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:: syntax error in expression (error token is "64-Bit Server VM warning: Insufficient space for shared memory file:")
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
