### ISSUE TITLE
Errors while running the given test (probably caused by rpsbproc)

### ISSUE THREAD

**Issue by hyl317** [ebi-pf-team/interproscan#98]
While running the simple test command
`./interproscan.sh -i test_proteins.fasta -f tsv`
Can someone point out what the problem is and how can I fix it?

09/07/2019 11:08:30:246 25% completed
2019-07-09 11:08:51,881 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

2019-07-09 11:08:51,886 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2019-07-09 11:08:51,887 [amqEmbeddedWorkerJmsContainer-6] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepCDDRunPostBlastProcessing
2019-07-09 11:08:51,940 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 43 is being re-run following a failure.
09/07/2019 11:08:54:397 51% completed
2019-07-09 11:08:57,051 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

2019-07-09 11:08:57,052 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2019-07-09 11:08:57,053 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepCDDRunPostBlastProcessing
2019-07-09 11:08:57,120 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 43 is being re-run following a failure.
2019-07-09 11:09:03,323 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

2019-07-09 11:09:03,324 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 127
Command: bin/blast/ncbi-blast-2.9.0+/rpsbproc -i /home/yh362/tools/interproscan/interproscan-5.36-75.0/temp/mocha_20190709_110754152_fin//jobCDD/000000000001_000000000006.blast.raw.out -d data/cdd/3.17/data -m std 
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
2019-07-09 11:09:03,326 [amqEmbeddedWorkerJmsContainer-4] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepCDDRunPostBlastProcessing
2019-07-09 11:09:03,481 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 43 : Run CDD Binary rpsbproc. for selected proteins for proteins 1 to 6 has failed irretrievably.  Available StackTraces follow.
2019-07-09 11:09:03,482 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2019-07-09 11:09:03,482 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:285] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:147)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:399)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by ta-cameron** [comment]
You needs to install elfutils so that the libdw.so.1 library it complains about is available. This can be done using apt-get install elfutils

**Comment by webbchen** [comment]
I had the same issue and reinstalling rpsblast and rpsproc repaired it.
Please note: The link provided to in the [compiling binaries](https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries) section :
```
wget -r --no-parent -l 1 -np -nd -nH -P rpsbproc ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-src/
```
is dead as rpsbproc-src comes as a tar.gz archive which needs to be retrieved like so:
```
wget ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd/rpsbproc/rpsbproc-0.5.0-src.tar.gz
tar xvzf rpsbproc-0.5.0-src.tar.gz
```
With everything else proceed as it says (apart from the current blast version being 2.9.0, adapt filenames accordingly) and it may well work then, it did for me.
Good luck!

**Comment by Sidduppal** [comment]
For someone slow to learn like me (who wasted hours pulling his hair out) you need to export the path to the directory where `conda` installs `elfutils`. 
Walkthrough:

```bash
conda create --name interproscan python=3.7 -y
conda activate interproscan
conda install -c conda-forge elfutils -y
export LD_LIBRARY_PATH="/home/<user_name>/miniconda3/pkgs/elfutils-0.182-h99488e9_1/lib"
# to test if everything is working
./interproscan.sh -i test_proteins.fasta -dp
```
