### ISSUE TITLE
Cannot run program "bin/phobius/1.01/phobius.pl": error=2, No existe el fichero o el directorio

### ISSUE THREAD

**Issue by elainfl** [ebi-pf-team/interproscan#99]
Dear all, 

I tried to run Interproscan, following the indications and installing additional programmes at the proper paths. I kept having issues and I decided to install the last version from 5 days ago. I re-run the program and I had the following issue: 

`Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
10/07/2019 15:15:24:416 Uploaded/Stored 38672 unique sequences for analysis
2019-07-10 18:30:52,681 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "bin/phobius/1.01/phobius.pl": error=2, No existe el fichero o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2019-07-10 18:30:52,689 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPhobiusRunBinary
2019-07-10 18:30:52,816 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 958 is being re-run following a failure.`

It says that there is no binary file for Phobius programme but it is there. 

`/programasseq/interproscan-5.36-75.0/bin/phobius/1.01$ ls -lh
total 1,4M
-rwxr-x--- 1 elena elena 133K jul 30  2004 decodeanhmm
-rwxr-x--- 1 elena elena 1,2M jul 28  2017 decodeanhmm.64bit
-rw-r--r-- 1 elena elena  209 jul 10 15:10 LicenseAgreement.txt
-rwxr-x--- 1 elena elena  384 ene 25  2007 OPSD_SHEEP
-rw-r----- 1 elena elena  29K dic  3  2004 phobius.model
-rw-r----- 1 elena elena 1022 dic  3  2004 phobius.options
-rwxr-x--- 1 elena elena  12K feb 14  2005 phobius.pl
-rw-r----- 1 elena elena  605 nov 23  2007 Q8TCT8
-rw-r----- 1 elena elena  929 feb 14  2005 README
`
What can I do? 

Thanks

**Comment by elainfl** [comment]
Sorry I will copy the code again

Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
10/07/2019 15:15:24:416 Uploaded/Stored 38672 unique sequences for analysis
2019-07-10 18:30:52,681 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "bin/phobius/1.01/phobius.pl": error=2, No existe el fichero o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2019-07-10 18:30:52,689 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepPhobiusRunBinary
2019-07-10 18:30:52,816 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:156] WARN - StepInstance 958 is being re-run following a failure.


ls -lh
total 1,4M
-rwxr-x--- 1 elena elena 133K jul 30  2004 decodeanhmm
-rwxr-x--- 1 elena elena 1,2M jul 28  2017 decodeanhmm.64bit
-rw-r--r-- 1 elena elena  209 jul 10 15:10 LicenseAgreement.txt
-rwxr-x--- 1 elena elena  384 ene 25  2007 OPSD_SHEEP
-rw-r----- 1 elena elena  29K dic  3  2004 phobius.model
-rw-r----- 1 elena elena 1022 dic  3  2004 phobius.options
-rwxr-x--- 1 elena elena  12K feb 14  2005 phobius.pl
-rw-r----- 1 elena elena  605 nov 23  2007 Q8TCT8
-rw-r----- 1 elena elena  929 feb 14  2005 README

**Comment by gsn7** [comment]
sorryi missed this issue. did you have it resolved?

**Comment by gsn7** [comment]
i will close this issue, if required open a new ticket
